// aidepost.com — the twenty-five, each checked against the built bytes.
// Every probe names something that would vanish if the feature were removed.

export const FEATURES = [
  { id: 'ap-01', name: 'The two-sided switch', kind: 'header',
    what: 'A segmented switch in the header — I run a house | I’m a caregiver — sets html[data-side], which swaps the nav set, the CTA label, the header’s tone and the footer’s; remembered between visits. On phones the CTA is sticky and compact and follows the side.',
    probe: [{ home: 'class="sw-b is-prov"' }, { home: 'data-set="caregiver"' }, { js: "store.set('ap-side'" }, { css: 'html[data-side="caregiver"] .hd' }, { css: '.hd-cta .l-short' }] },
  { id: 'ap-02', name: 'The split sheet', kind: 'mobile',
    what: 'The phone menu opens as a full-height sheet split in two: the light half lists the provider’s links, the dark half the caregiver’s; a link on either half also sets the side.',
    probe: [{ home: 'class="sheet-half is-care" data-side-half="caregiver"' }, { home: 'aria-controls="sheet"' }, { css: '.sheet-g{display:grid;grid-template-columns:1fr 1fr' }] },
  { id: 'ap-03', name: 'The bottom split bar', kind: 'mobile',
    what: 'A fixed bar on phones, two halves — For providers, light; For caregivers, dark — each scrolling to its half of the page and setting the side; the mark is the pin between them and leans toward the active side.',
    probe: [{ home: '<nav class="bar" aria-label="Two sides">' }, { home: 'class="bar-pin"' }, { css: 'html[data-side="caregiver"] .bar-pin .mk' }, { css: '.page{padding-bottom:calc(var(--bar-h)' }] },
  { id: 'ap-04', name: '⌘K, the verbs', kind: 'navigation',
    what: 'A command palette with Aidepost’s own verbs — Offer to own staff, Post outward, Add a credential date, Export timesheets — plus the page’s: each runs the thing it names; filter by typing, arrows and Enter.',
    probe: [{ home: 'data-verb="offer"' }, { home: 'aria-controls="pal"' }, { js: "v === 'export'" }, { js: "e.key.toLowerCase() === 'k'" }] },
  { id: 'ap-05', name: 'Day | Night, the shift badge', kind: 'dark',
    what: 'The light switch is drawn as a shift badge — Day | Night — and remembers itself; Night turns the provider side plum-black, and the caregiver side stays the night it already was.',
    probe: [{ home: 'class="badge-t" type="button" data-mode-toggle' }, { css: 'html[data-mode="dark"]{--bg:#1C1620' }, { css: '.badge-t[aria-pressed="true"] .badge-pin' }] },
  { id: 'ap-06', name: 'The real day', kind: 'interaction',
    what: 'The headline says Someone for Saturday night; the script counts to the coming Saturday — That’s tonight, tomorrow night, in N days — lights Saturday and today on the board, and a strip under it names who is on tonight from the roster row for the real weekday.',
    probe: [{ home: 'class="hero-live" data-live' }, { home: 'data-tonight' }, { js: '(6 - dow + 7) % 7' }, { css: '.board th.is-today .board-d::after' }] },
  { id: 'ap-07', name: 'The claim: Saturday night gets covered', kind: 'interaction',
    what: 'Tap the Open cell: a sheet offers the shift to own staff (three names, two markers, nobody removed), posts it outward, R. Alvarez claims, you confirm — the cell turns covered and a record line shows you offered inward first. Reset restores it. Share this shift deep-links #board.',
    probe: [{ home: 'data-cell-open aria-controls="claim"' }, { home: 'data-claim-act="confirm"' }, { home: 'data-share="https://aidepost.com/#board"' }, { js: "cellT.textContent = 'R. Alvarez'" }] },
  { id: 'ap-08', name: 'The credential timeline', kind: 'interaction',
    what: 'A slider through the days before and after a First Aid card expires moves the card through Current → thirty-day notice → seven-day notice → Expired, each with what the product actually does — and none of them blocks an assignment.',
    probe: [{ home: 'data-tl-in' }, { home: 'data-tl-card data-state="current"' }, { js: "days < 0 ? 'expired' : days <= 7 ? 'notice7'" }, { css: '.tl-card[data-state="expired"]' }] },
  { id: 'ap-09', name: 'The roster builder', kind: 'interaction',
    what: 'A seven-by-two week you can build: every cell is a button that cycles M. Okafor → J. Ruiz → T. Nguyen → Open, and the coverage count updates — 13 of 14, or fewer.',
    probe: [{ home: 'data-ros data-names="M. Okafor|J. Ruiz|T. Nguyen"' }, { home: 'class="ros-c is-open"' }, { js: '(Number(b.dataset.who) + 1) % 4' }] },
  { id: 'ap-10', name: 'The timesheet, weekly flag only', kind: 'interaction',
    what: 'Seven day bars you can toggle; the weekly total recomputes and the forty-hour flag appears or goes — weekly, never daily — with an Export CSV that says hours, never pay.',
    probe: [{ home: 'class="ts-d" type="button" data-h="8" aria-pressed="true"' }, { home: 'data-ts-export' }, { js: 'weekly flag, never daily' }, { css: '.ts-f.is-over' }] },
  { id: 'ap-11', name: 'Clock in at the house', kind: 'interaction',
    what: 'Press Clock in and a ring closes around the house pin, stamped with the live time and WH-1; press again to clock out. The copy says what queues offline and what never does.',
    probe: [{ home: 'data-ck-btn' }, { home: 'class="ck-arc"' }, { js: 'Clocked in at ${time()} · WH-1' }, { css: '.ck.is-in .ck-arc{stroke-dashoffset:0' }] },
  { id: 'ap-12', name: 'The distance slider, on the page and in the phone', kind: 'screen',
    what: 'On the dark half, a slider from 2 to 25 miles filters the three demo offers on the page and dims the same rows inside the caregiver phone beside it — the screen answers the control.',
    probe: [{ home: 'data-dist-in' }, { home: 'class="offer" data-mi="4.2"' }, { js: "rows[i].classList.toggle('is-far', far)" }, { css: '.phone .row-a.is-far' }] },
  { id: 'ap-13', name: 'Roles as flip cards', kind: 'interaction',
    what: 'Five roles, each a card that turns over — tap, click or press Enter — to show what that role may do and on which device; two of them have no employer and are drawn on the dark side.',
    probe: [{ home: '<details class="flip ' }, { home: 'class="flip-b"' }, { css: '.flip[open]{transform:rotateY(180deg)' }] },
  { id: 'ap-14', name: 'The notification', kind: 'interaction',
    what: 'When the board comes into view a phone-style banner slides in — WH-1: Sat night is open — once per visit; tapping it opens the claim sheet, dismissing it puts it away.',
    probe: [{ home: 'id="ntf"' }, { home: 'WH-1: Sat night is open.' }, { js: "sess.get('ap-ntf')" }, { css: '.ntf.is-on' }] },
  { id: 'ap-15', name: 'Per post, and the caregiver exception', kind: 'interaction',
    what: 'Providers | Caregivers on the pricing block: the provider side lists the tiers, and the Job post tier opens to say what one charge buys; the caregiver side shows $0, for ever — the documented exception.',
    probe: [{ home: '<details class="tier is-post">' }, { home: '$0, for ever' }, { home: 'class="pr-b is-care" type="button" data-side-set="caregiver"' }, { css: 'html[data-side="caregiver"] .pr .s-care' }] },
  { id: 'ap-16', name: 'Keyboard: 1, 2, ⌘K, ?, Esc', kind: 'a11y',
    what: '1 and 2 switch sides, ⌘K opens the verbs, ? opens a shortcut card, Escape closes whatever is open; every panel is a real dialog reachable from a button as well.',
    probe: [{ home: 'aria-controls="keys"' }, { home: '<kbd>?</kbd>' }, { js: "e.key === '1'" }, { js: "e.key === '?'" }] },
  { id: 'ap-17', name: 'The boundary follows the pointer', kind: 'motion',
    what: 'The two doors share one band; the light/dark boundary between them is a clip-path that eases toward the cursor on a desktop, splits 50/50 on touch, and stays still under reduced motion.',
    probe: [{ home: 'data-doors style="--x:50%"' }, { css: 'clip-path:polygon(var(--x) 0' }, { js: "d.style.setProperty('--x'" }, { js: 'calm.matches ||' }] },
  { id: 'ap-18', name: 'The refusals as a deck', kind: 'mobile',
    what: 'Seven refusals as a swipeable, snapping card deck on a phone with previous/next and dots — and a grid on a desktop.',
    probe: [{ home: 'class="deck-r" data-scrollx' }, { home: 'data-deck-next' }, { css: '.deck-c{flex:0 0 min(340px,82%)' }, { js: 'data-deck-dots' }] },
  { id: 'ap-19', name: 'The board as a snapping week with initials', kind: 'mobile',
    what: 'On a phone the hero board keeps all seven days: covered cells carry initials, the open cell stays a 44px button, and the week snaps sideways when it must scroll.',
    probe: [{ home: 'class="cell-i" aria-hidden="true">MO' }, { css: '.board-w{margin-top:clamp(36px,5vw,64px);overflow-x:auto' }, { css: '.cell-i{display:block}' }] },
  { id: 'ap-20', name: 'Print the roster', kind: 'print',
    what: 'Print this week on the board, or Print the roster in the footer, prints the week board — and nothing else on the page.',
    probe: [{ home: 'class="btn sm ft-print" type="button" data-print' }, { css: '@media print' }, { css: 'main>:not(.hero):not(#board){display:none' }] },
  { id: 'ap-21', name: 'Spotlights on the annotated board', kind: 'screen',
    what: 'The five callouts under the desktop board are buttons: press one and the thing it quotes — the covered cell, the open cell, the detail card, the two actions, the side rail — is ringed on the screen itself and scrolled into view.',
    probe: [{ home: 'class="an-b" type="button" data-spot="2"' }, { home: 'data-shell' }, { js: "'.wk-cell[data-state=\"open\"]'" }, { css: '.shell .is-spot::after{content:attr(data-spot-n)' }] },
  { id: 'ap-22', name: 'Two doors at depth: /providers and /caregivers', kind: 'page',
    what: 'The provider page walks four screens — board, credentials, hours, hiring — with the nine flows and their state tables, under a sticky chapter strip that snaps on a phone; the caregiver page is dark end to end, with the rules that protect a worker.',
    probe: [{ route: 'providers' }, { route: 'caregivers' }, { html: 'class="chap" aria-label="Chapters" data-spy data-chap' }, { html: 'class="prot-g"' }] },
  { id: 'ap-23', name: 'Write to a person, with topics', kind: 'page',
    what: 'The contact page carries the kit’s form with Aidepost’s topics — Question, Early access, I’m a caregiver, Pricing, Security and privacy, Press, Something else — and two addresses with a copy button each: caregiver@aidepost.com for the free side, shifts@aidepost.com for everything else. Nothing else on the site asserts the caregiver address, so the last two probes pin it in the built bytes of /caregivers.',
    probe: [{ route: 'contact' }, { html: '<option value="I’m a caregiver">' }, { html: 'id="contactform"' }, { route: 'caregivers' }, { html: 'mailto:caregiver@aidepost.com' }] },
  { id: 'ap-24', name: 'The footer is the week', kind: 'footer',
    what: 'Seven columns, Monday to Sunday — Product, Caregivers, Company, Oregon, Write with the page’s own address and a copy button, Social, and Sunday holding the mark and the byline. The real weekday is lit “tonight”; on phones it becomes two columns with the weekend full width.',
    probe: [{ home: 'class="ft-d" data-day="Thu"' }, { home: 'data-clock="day"' }, { home: 'data-copy="shifts@aidepost.com"' }, { js: "el.toggleAttribute('data-today'" }, { css: '.ft-d[data-today]' }] },
  { id: 'ap-25', name: 'Social pills, with the pin', kind: 'social',
    what: 'Eight platforms as pill-shaped glyphs, each with the badge set’s pin in the corner; on the caregiver side the whole footer turns over and the pills invert with it.',
    probe: [{ home: 'class="soc soc-pills"' }, { css: '.soc-pills .soc-i::after' }, { css: 'html[data-side="caregiver"] .soc-pills .soc-i' }] },

  /* ══ THE WORKING DEMO ═══════════════════════════════════════════════
     Twenty-five more, and the direction is one sentence: a partner with
     ninety seconds must be able to OPERATE Aidepost inside the page and
     leave knowing why the two-sided shape wins. Every probe below names
     something that stops existing if the feature is deleted. */

  { id: 'ap-26', name: 'All five screens, in one rail', kind: 'screen',
    what: '/screens carries every real Aidepost screen — board, credentials, her side, timesheets, posts — in one full-bleed rail that snaps, drags, takes the arrow keys and announces where it is; each card is captioned with what it is and with what it proves.',
    probe: [{ route: 'screens' }, { html: 'class="fs-rail" id="strip-rail"' }, { html: 'id="strip-caregiver"' }, { html: 'What this proves' },
      { js: "STEP = { ArrowLeft: -1, ArrowRight: 1, Home: 'h', End: 'e' }" }, { js: "' of ' + el.length + ', '" }] },
  { id: 'ap-27', name: 'The hero device takes the side', kind: 'interaction',
    what: 'On /screens the hero device is a real tablist — I run a house | I’m a caregiver — with no layout shift between panels, wired to the site-wide switch in both directions: flip the site and the device follows; press a tab and the whole site turns over.',
    probe: [{ html: 'id="sw-sides"' }, { html: 'aria-controls="sw-sides-p1"' }, { js: "getElementById('sw-sides')" }, { js: "b.dataset.swTo === '1'" }, { css: '.hero-sc .hero-dw' }] },
  { id: 'ap-28', name: 'Five pins on the hiring screen', kind: 'screen',
    what: 'The desktop hiring shell carries five numbered callouts. Point at one, or reach its sentence with a keyboard — every row in the list is focusable and lights the row, its pin and the element the sentence quotes. Four pins are placed from their element’s measured box and hide if it stops matching; the fifth names a coordinate on the house identifier in the top bar, which is a label with no selector of its own, so it lights but rings nothing.',
    probe: [{ html: 'id="cal-hire"' }, { html: 'data-sel=".page-side .tile-a"' }, { html: 'class="cal-i" tabindex="0"' }, { html: 'class="cal-pin" data-cal="5"' }, { css: '.cal-pin{background:var(--orchid)' },
      { js: "$$('.cal-pin[data-sel]', w)" }, { js: "document.addEventListener('focusin', light)" }] },
  { id: 'ap-29', name: 'The two-tone page index', kind: 'navigation',
    what: 'Six of the eight routes carry “On this page”: a scroll-tracking rail of that page’s own sections, each marked with the side it belongs to — ink for the provider, orchid for the caregiver — and the one you are inside takes aria-current. The two without it have nothing to index: /contact is a single section, and /privacy is drawn by the kit’s shared privacy page, whose one section this site does not author.',
    probe: [{ home: '<nav class="ix" aria-label="What is on this page" data-spy data-ix>' }, { home: 'data-side-hint="care"' }, { css: '.ix-l a[aria-current="true"]' },
      { js: "links.forEach((a, i) => { if (i === on) a.setAttribute('aria-current', 'true');" }] },
  { id: 'ap-30', name: 'Previous and next, across eight routes', kind: 'navigation',
    what: 'All eight pages end with the routes either side of them, each naming itself and what it holds, plus “n of 8”. It does not wrap: the front page has no previous and the eighth has no next, and neither draws the one it does not have. /privacy is rendered by the kit’s shared privacy page, so its pager is emitted by this site’s own footer — between the body and the footer — rather than by a body this site does not write.',
    probe: [{ home: '<nav class="pg" aria-label="The rest of the site, in order">' }, { home: 'class="pg-i is-next" href="/providers"' }, { html: 'class="pg-i is-prev" href="/about"' }, { html: 'class="pg-i is-prev" href="/contact"' }, { css: '.pg-i.is-next' }] },
  { id: 'ap-31', name: '⌘K goes places as well as doing things', kind: 'navigation',
    what: 'The palette now lists all eight routes beside the four verbs; typing filters both, arrows and Enter reach either, and every destination is a real anchor carrying its own path — so it still works with the script gone.',
    probe: [{ home: '<a class="pal-row is-go" href="/screens">' }, { home: 'class="pal-p">/privacy' }, { css: '.pal-row.is-go' }] },
  { id: 'ap-32', name: 'Where you are, in the header', kind: 'mobile',
    what: 'Below 900 the header names the route under the wordmark — Both sides, For providers, The screens — because a phone header has no section rail to infer it from. Above 900 the rail says it better and this goes.',
    probe: [{ home: 'class="hd-where" data-where>Both sides' }, { html: 'class="hd-where" data-where>The screens' }, { css: '.hd-where{display:flex;align-items:center' }] },
  { id: 'ap-33', name: 'The status ledger', kind: 'page',
    what: 'Six rows stating what is true today: the product is Draft v1.1 with no repository, the specification is written, this page is the only live thing, prices are Open (#8), caregivers are free permanently, and the largest open question is named rather than hidden.',
    probe: [{ home: 'role="table" aria-label="What is true today"' }, { home: 'class="led-s is-pending">Not set' }, { home: 'The largest open question' }, { css: '.led-s.is-covered::before' }] },
  { id: 'ap-34', name: 'The family band, live', kind: 'page',
    what: 'The other three rooms and the house above them, each with its own mark, its own live address and its own honest state — and a line saying what it takes off Aidepost’s plate, so the band is a boundary statement rather than a logo wall.',
    probe: [{ home: 'class="fam" href="https://careshop.app"' }, { home: 'class="fam-t">Takes the residents' }, { css: '.fam-t' }] },
  { id: 'ap-35', name: 'The graduation map', kind: 'page',
    what: '/about carries the five rows of the ladder into Provider Hub Oregon — staff and credentials, shifts and clock events, posts and applications, the relief pool, acknowledgments — each naming the PHO module it lands in, with the claim stated as a claim.',
    probe: [{ route: 'about' }, { html: 'class="grd-l"' }, { html: 'M07 open shifts and talent pool' }, { css: '.grd-l li::before' }] },
  { id: 'ap-36', name: 'Copy the address of what you are reading', kind: 'interaction',
    what: 'The board, the ledger, the strip, the map and the graduation ladder each carry a Link button that copies the absolute address of that section on the route it is actually on — the ladder’s says /about, the board’s says /providers. An address without its route now throws at build time rather than shipping a link to the front page. Every screen in the rail has its own id too, so /screens#strip-caregiver opens on one screen, sideways.',
    probe: [{ home: 'data-copy="https://aidepost.com/#ledger"' }, { html: 'data-copy="https://aidepost.com/screens#strip"' }, { html: 'data-copy="https://aidepost.com/about#ladder"' }, { html: 'data-copy="https://aidepost.com/providers#board"' }, { home: 'href="/screens#strip-caregiver"' }, { css: '.dl{display:inline-flex' },
      { js: "await navigator.clipboard.writeText(text); toast(c.getAttribute('data-copied')" }] },
  { id: 'ap-37', name: 'The five screens, one tap from the top', kind: 'navigation',
    what: 'Under the front-page hero, five numbered chips deep-link into the rail on /screens — the four provider screens in ivory, her side in night — so the whole product is one tap from the first thing anybody sees. Both lists read their order from the same screen list, so chip 03 and card 03 are the same screen.',
    probe: [{ home: '<nav class="sj" aria-label="Jump straight to one screen">' }, { home: 'href="/screens#strip-hire"' }, { home: '<span class="sj-n">03</span>Her side' }, { css: '.sj-l a[data-side-hint="care"]' }] },
  { id: 'ap-38', name: 'Four words, and no fifth colour', kind: 'page',
    what: 'The four state words this product owns — covered, open, pending, expired — with what each one means, and the statement that expired borrows Cohort’s coral rather than inventing a fifth colour for the family.',
    probe: [{ html: 'class="stl-i is-expired"' }, { html: 'borrows Cohort’s accent here' }, { css: '.stl-i.is-expired .stl-d' }] },
  { id: 'ap-39', name: 'Every field on a shift, and the one that is not', kind: 'page',
    what: 'The nine fields a shift record carries, listed — and then the field that is absent, with the schema check that asserts it and the rule that finding one in review is a blocker, not a finding.',
    probe: [{ route: 'screens' }, { html: 'class="schm-f"' }, { html: 'a code review that finds one is a blocker, not a finding' }] },
  { id: 'ap-40', name: '/screens: operate it without signing up', kind: 'page',
    what: 'A route whose whole job is the demo — the two-sided hero device, the rail of five, the annotated desktop, the state words, the record and the map — with its own index and no form anywhere on it.',
    probe: [{ route: 'screens' }, { html: 'Both sides, screen by screen.' }, { html: 'data-strip="aidepost"' }] },
  { id: 'ap-41', name: 'Every sentence Aidepost can send', kind: 'page',
    what: 'Sixteen messages may be sent at all, and the send function takes an event key and references — there is no body parameter. Both real renderings are printed: the email and the push, including why a time renders as “Sat night” and never as a clock time.',
    probe: [{ html: 'class="msg-q">WH-1: 2 shifts open within 24 hours.' }, { html: 'no body parameter' }, { css: '.msg-q' }] },
  { id: 'ap-42', name: 'The first ten minutes, ticked off', kind: 'interaction',
    what: 'The four things brand.js says you do on day one, as checkboxes you can tick against the rail above — :checked strikes the line through, and it costs no script at all.',
    probe: [{ html: 'class="ft10-x" type="checkbox" id="ft10-3"' }, { html: 'See the one that expires Friday turn coral.' }, { css: '.ft10-x:checked' }] },
  { id: 'ap-43', name: 'What it refuses, and who holds it instead', kind: 'page',
    what: 'Aidepost’s own doesNot list, rendered verbatim: payroll and background checks go to the provider, resident care to Cohort, the house rules to Binderkit — and each card links to the room that holds it.',
    probe: [{ home: 'class="dn" aria-label="What Aidepost does not do, and who does it instead"' }, { home: '<b>Hold resident care, MAR or incidents</b><span><a href="https://cohorthome.app"' }, { css: '.dn b::before' }] },
  { id: 'ap-44', name: 'The whole product, in eight destinations', kind: 'page',
    what: 'The product’s own navigation, printed: The workforce — shifts, staff, credentials, onboarding, timesheets, posts — and Organisation — houses, settings — plus the five phone tabs. There is no second Aidepost behind a sales call.',
    probe: [{ route: 'screens' }, { html: 'class="pmap-c"' }, { css: '.pmap-c li' }] },
  { id: 'ap-45', name: 'What is invented here, named', kind: 'page',
    what: 'A disclosure listing exactly which parts of the demo are fiction — the house codes, the names, the dates, the rate, the distances — and which are the specification, and that no customer, pilot, metric or raise appears anywhere because there is none to report.',
    probe: [{ html: 'What on these screens is invented, exactly' }, { html: 'class="smp"' }, { css: '.smp>summary' }] },
  { id: 'ap-46', name: 'The rail is in the shortcut card', kind: 'a11y',
    what: 'The keyboard card now carries the rail: arrows move through the screens in the strip and in the tabs, Home and End reach the first and the last. The rail itself is focusable, so a keyboard reaches it without a mouse.',
    probe: [{ home: 'Move through the screens — in the strip, or in the tabs' }, { html: 'role="list" tabindex="0"' }, { home: 'The verbs, and every page' }] },
  { id: 'ap-47', name: 'The lit destination scrolls itself into view', kind: 'mobile',
    what: 'Both scroll-spy rails — the desktop chapter strip and the page index — keep the destination you are inside centred as you scroll. On a 390 phone the index row is 350px wide, 102px of it the label, so its fourteen front-page destinations move through a 240px window: without the auto-centre the destination you are inside is almost never the one on screen.',
    probe: [{ js: '[data-chap],[data-ix]' }, { js: 'ul.scrollTo({ left: a.offsetLeft' }] },
  { id: 'ap-48', name: 'The new sections fold like the old ones', kind: 'mobile',
    what: 'The ledger and the family band join the phone fold: each collapses to one row carrying its own heading and gist, so adding two sections to the front page costs a phone reader two rows rather than two screens.',
    probe: [{ home: 'data-gist="Four rooms, one ladder' }, { home: 'data-gist="What is live, what is not' }, { css: '[data-phone="fold"]>[hidden]{display:none}' },
      { js: "if (s.dataset.gist) { const g = document.createElement('span'); g.className = 'fold-g';" }] },
  { id: 'ap-49', name: 'The phone, thirteen per cent denser', kind: 'mobile',
    what: 'Every hand-typed margin, padding, min-height and row gap in this sheet comes down below 640 — the step crop from 260px to 200px, .care onto the shared --sec-y, the board cell keeping its 44px floor and giving back only the padding above it. Measured at 390 against the build before it: −13.0% across the forty-two sections present in both, −14.2% on the front page, −11.2% on /about’s four. Across whole routes it is −1.0%, because the same round added four sections, six page indexes and eight pagers to them — /about reads +62.5% for that reason and no other. None of these numbers is a fifth, and the feature is not named for one.',
    probe: [{ css: '.step .crop{margin:8px -8px 0;height:200px}' }, { css: '.care{padding-block:var(--sec-y)}' }, { css: '@media (min-width:641px){#caregivers.care h2' }] },
  { id: 'ap-50', name: 'The contact form arrives on your side', kind: 'interaction',
    what: 'The topic select follows the side you are on — a caregiver who has spent the page on the dark half lands on “I’m a caregiver” — and stops following the moment she touches it.',
    probe: [{ js: '#contactform select[name="topic"]' }, { html: '<option value="I’m a caregiver">' }, { route: 'contact' }] },
];

export default FEATURES;
