// aidepost.com — the twenty-five, each checked against the built bytes.
// Every probe names something that would vanish if the feature were removed.

export const FEATURES = [
  { id: 'ap-01', name: 'The two-sided switch', kind: 'header',
    what: 'A segmented switch in the header — I run a house | I’m a caregiver — sets html[data-side], which swaps the nav set, the CTA label, the header’s tone and the footer’s; remembered between visits. On phones the CTA is sticky and compact and follows the side.',
    probe: [{ home: 'class="sw-b is-prov"' }, { home: 'data-set="caregiver"' }, { js: "store.set('ap-side'" }, { css: 'html[data-side="caregiver"] .hd' }, { css: '.hd-cta .l-short' }] },
  { id: 'ap-02', name: 'The split sheet', kind: 'mobile',
    what: 'The phone menu opens as a full-height sheet split in two: the light half lists the provider’s links, the dark half the caregiver’s; a link on either half also sets the side.',
    probe: [{ home: 'class="sheet-half is-care" data-side-half="caregiver"' }, { home: 'aria-controls="sheet"' }, { css: '.sheet-g{display:grid;grid-template-columns:1fr 1fr' }] },
  { id: 'ap-03', name: 'The bottom split bar', kind: 'mobile',
    what: 'A fixed bar on phones, two halves — For providers, light; For caregivers, dark — each scrolling to its half of the page and setting the side; the mark is the pin between them and leans toward the active side.',
    probe: [{ home: '<nav class="bar" aria-label="Two sides">' }, { home: 'class="bar-pin"' }, { css: 'html[data-side="caregiver"] .bar-pin .mk' }, { css: '.page{padding-bottom:calc(var(--bar-h)' }] },
  { id: 'ap-04', name: '⌘K, the verbs', kind: 'navigation',
    what: 'A command palette with Aidepost’s own verbs — Offer to own staff, Post outward, Add a credential date, Export timesheets — plus the page’s: each runs the thing it names; filter by typing, arrows and Enter.',
    probe: [{ home: 'data-verb="offer"' }, { home: 'aria-controls="pal"' }, { js: "v === 'export'" }, { js: "e.key.toLowerCase() === 'k'" }] },
  { id: 'ap-05', name: 'Day | Night, the shift badge', kind: 'dark',
    what: 'The light switch is drawn as a shift badge — Day | Night — and remembers itself; Night turns the provider side plum-black, and the caregiver side stays the night it already was.',
    probe: [{ home: 'class="badge-t" type="button" data-mode-toggle' }, { css: 'html[data-mode="dark"]{--bg:#1C1620' }, { css: '.badge-t[aria-pressed="true"] .badge-pin' }] },
  { id: 'ap-06', name: 'The real day', kind: 'interaction',
    what: 'The headline says Someone for Saturday night; the script counts to the coming Saturday — That’s tonight, tomorrow night, in N days — lights Saturday and today on the board, and a strip under it names who is on tonight from the roster row for the real weekday.',
    probe: [{ home: 'class="hero-live" data-live' }, { home: 'data-tonight' }, { js: '(6 - dow + 7) % 7' }, { css: '.board th.is-today .board-d::after' }] },
  { id: 'ap-07', name: 'The claim: Saturday night gets covered', kind: 'interaction',
    what: 'Tap the Open cell: a sheet offers the shift to own staff (three names, two markers, nobody removed), posts it outward, R. Alvarez claims, you confirm — the cell turns covered and a record line shows you offered inward first. Reset restores it. Share this shift deep-links #board.',
    probe: [{ home: 'data-cell-open aria-controls="claim"' }, { home: 'data-claim-act="confirm"' }, { home: 'data-share="https://aidepost.com/#board"' }, { js: "cellT.textContent = 'R. Alvarez'" }] },
  { id: 'ap-08', name: 'The credential timeline', kind: 'interaction',
    what: 'A slider through the days before and after a First Aid card expires moves the card through Current → thirty-day notice → seven-day notice → Expired, each with what the product actually does — and none of them blocks an assignment.',
    probe: [{ home: 'data-tl-in' }, { home: 'data-tl-card data-state="current"' }, { js: "days < 0 ? 'expired' : days <= 7 ? 'notice7'" }, { css: '.tl-card[data-state="expired"]' }] },
  { id: 'ap-09', name: 'The roster builder', kind: 'interaction',
    what: 'A seven-by-two week you can build: every cell is a button that cycles M. Okafor → J. Ruiz → T. Nguyen → Open, and the coverage count updates — 13 of 14, or fewer.',
    probe: [{ home: 'data-ros data-names="M. Okafor|J. Ruiz|T. Nguyen"' }, { home: 'class="ros-c is-open"' }, { js: '(Number(b.dataset.who) + 1) % 4' }] },
  { id: 'ap-10', name: 'The timesheet, weekly flag only', kind: 'interaction',
    what: 'Seven day bars you can toggle; the weekly total recomputes and the forty-hour flag appears or goes — weekly, never daily — with an Export CSV that says hours, never pay.',
    probe: [{ home: 'class="ts-d" type="button" data-h="8" aria-pressed="true"' }, { home: 'data-ts-export' }, { js: 'weekly flag, never daily' }, { css: '.ts-f.is-over' }] },
  { id: 'ap-11', name: 'Clock in at the house', kind: 'interaction',
    what: 'Press Clock in and a ring closes around the house pin, stamped with the live time and WH-1; press again to clock out. The copy says what queues offline and what never does.',
    probe: [{ home: 'data-ck-btn' }, { home: 'class="ck-arc"' }, { js: 'Clocked in at ${time()} · WH-1' }, { css: '.ck.is-in .ck-arc{stroke-dashoffset:0' }] },
  { id: 'ap-12', name: 'The distance slider, on the page and in the phone', kind: 'screen',
    what: 'On the dark half, a slider from 2 to 25 miles filters the three demo offers on the page and dims the same rows inside the caregiver phone beside it — the screen answers the control.',
    probe: [{ home: 'data-dist-in' }, { home: 'class="offer" data-mi="4.2"' }, { js: "rows[i].classList.toggle('is-far', far)" }, { css: '.phone .row-a.is-far' }] },
  { id: 'ap-13', name: 'Roles as flip cards', kind: 'interaction',
    what: 'Five roles, each a card that turns over — tap, click or press Enter — to show what that role may do and on which device; two of them have no employer and are drawn on the dark side.',
    probe: [{ home: '<details class="flip ' }, { home: 'class="flip-b"' }, { css: '.flip[open]{transform:rotateY(180deg)' }] },
  { id: 'ap-14', name: 'The notification', kind: 'interaction',
    what: 'When the board comes into view a phone-style banner slides in — WH-1: Sat night is open — once per visit; tapping it opens the claim sheet, dismissing it puts it away.',
    probe: [{ home: 'id="ntf"' }, { home: 'WH-1: Sat night is open.' }, { js: "sess.get('ap-ntf')" }, { css: '.ntf.is-on' }] },
  { id: 'ap-15', name: 'Per post, and the caregiver exception', kind: 'interaction',
    what: 'Providers | Caregivers on the pricing block: the provider side lists the tiers, and the Job post tier opens to say what one charge buys; the caregiver side shows $0, for ever — the documented exception.',
    probe: [{ home: '<details class="tier is-post">' }, { home: '$0, for ever' }, { home: 'class="pr-b is-care" type="button" data-side-set="caregiver"' }, { css: 'html[data-side="caregiver"] .pr .s-care' }] },
  { id: 'ap-16', name: 'Keyboard: 1, 2, ⌘K, ?, Esc', kind: 'a11y',
    what: '1 and 2 switch sides, ⌘K opens the verbs, ? opens a shortcut card, Escape closes whatever is open; every panel is a real dialog reachable from a button as well.',
    probe: [{ home: 'aria-controls="keys"' }, { home: '<kbd>?</kbd>' }, { js: "e.key === '1'" }, { js: "e.key === '?'" }] },
  { id: 'ap-17', name: 'The boundary follows the pointer', kind: 'motion',
    what: 'The two doors share one band; the light/dark boundary between them is a clip-path that eases toward the cursor on a desktop, splits 50/50 on touch, and stays still under reduced motion.',
    probe: [{ home: 'data-doors style="--x:50%"' }, { css: 'clip-path:polygon(var(--x) 0' }, { js: "d.style.setProperty('--x'" }, { js: 'calm.matches ||' }] },
  { id: 'ap-18', name: 'The refusals as a deck', kind: 'mobile',
    what: 'Seven refusals as a swipeable, snapping card deck on a phone with previous/next and dots — and a grid on a desktop.',
    probe: [{ home: 'class="deck-r" data-scrollx' }, { home: 'data-deck-next' }, { css: '.deck-c{flex:0 0 min(340px,82%)' }, { js: 'data-deck-dots' }] },
  { id: 'ap-19', name: 'The board as a snapping week with initials', kind: 'mobile',
    what: 'On a phone the hero board keeps all seven days: covered cells carry initials, the open cell stays a 44px button, and the week snaps sideways when it must scroll.',
    probe: [{ home: 'class="cell-i" aria-hidden="true">MO' }, { css: '.board-w{margin-top:clamp(36px,5vw,64px);overflow-x:auto' }, { css: '.cell-i{display:block}' }] },
  { id: 'ap-20', name: 'Print the roster', kind: 'print',
    what: 'Print this week on the board, or Print the roster in the footer, prints the week board — and nothing else on the page.',
    probe: [{ home: 'class="btn sm ft-print" type="button" data-print' }, { css: '@media print' }, { css: 'main>:not(.hero):not(#board){display:none' }] },
  { id: 'ap-21', name: 'Spotlights on the annotated board', kind: 'screen',
    what: 'The five callouts under the desktop board are buttons: press one and the thing it quotes — the covered cell, the open cell, the detail card, the two actions, the side rail — is ringed on the screen itself and scrolled into view.',
    probe: [{ home: 'class="an-b" type="button" data-spot="2"' }, { home: 'data-shell' }, { js: "'.wk-cell[data-state=\"open\"]'" }, { css: '.shell .is-spot::after{content:attr(data-spot-n)' }] },
  { id: 'ap-22', name: 'Two doors at depth: /providers and /caregivers', kind: 'page',
    what: 'The provider page walks four screens — board, credentials, hours, hiring — with the nine flows and their state tables, under a sticky chapter strip that snaps on a phone; the caregiver page is dark end to end, with the rules that protect a worker.',
    probe: [{ route: 'providers' }, { route: 'caregivers' }, { html: 'class="chap" aria-label="Chapters" data-spy data-chap' }, { html: 'class="prot-g"' }] },
  { id: 'ap-23', name: 'Write to a person, with topics', kind: 'page',
    what: 'The contact page carries the kit’s form with Aidepost’s topics — Question, Early access, I’m a caregiver, Pricing, Security and privacy, Press, Something else — and the address with a copy button.',
    probe: [{ route: 'contact' }, { html: '<option value="I’m a caregiver">' }, { html: 'id="contactform"' }] },
  { id: 'ap-24', name: 'The footer is the week', kind: 'footer',
    what: 'Seven columns, Monday to Sunday — Product, Caregivers, Company, Oregon, Write with hello@ and a copy button, Social, and Sunday holding the mark and the byline. The real weekday is lit “tonight”; on phones it becomes two columns with the weekend full width.',
    probe: [{ home: 'class="ft-d" data-day="Thu"' }, { home: 'data-clock="day"' }, { home: 'data-copy="hello@aidepost.com"' }, { js: "el.toggleAttribute('data-today'" }, { css: '.ft-d[data-today]' }] },
  { id: 'ap-25', name: 'Social pills, with the pin', kind: 'social',
    what: 'Eight platforms as pill-shaped glyphs, each with the badge set’s pin in the corner; on the caregiver side the whole footer turns over and the pills invert with it.',
    probe: [{ home: 'class="soc soc-pills"' }, { css: '.soc-pills .soc-i::after' }, { css: 'html[data-side="caregiver"] .soc-pills .soc-i' }] },
];

export default FEATURES;
