// aidepost.com — the features, each checked against the built bytes.
// Every probe names something that would vanish if the feature were removed.
// Rewritten 2026-09-23: the family band, the refusals deck, the pager and the
// sample-data note are gone; the phone board, the fit quiz, the credential
// rail, the wallet glyphs, the chip annotations and the reach block are in.

export const FEATURES = [
  { id: 'ap-01', name: 'The two-sided switch', kind: 'header',
    what: 'I run a house | I’m a caregiver sets html[data-side], which swaps the nav set, the CTA label and the footer’s tone; remembered between visits.',
    probe: [{ home: 'class="sw-b is-prov"' }, { home: 'data-set="caregiver"' }, { js: "store.set('ap-side'" }, { css: 'html[data-side="caregiver"] .hd' }, { css: '.hd-cta .l-short' }] },
  { id: 'ap-02', name: 'The nav wears its glyphs', kind: 'header',
    what: 'Every section link in the header carries a badge-set glyph — the board, the credential badge, the clock, the price tag — and the caregiver set carries the orchid pin.',
    probe: [{ home: 'class="ic-aidepost nav-ic"' }, { css: '.nav-ic{' }, { home: 'data-set="provider"' }] },
  { id: 'ap-03', name: 'The split sheet', kind: 'mobile',
    what: 'The phone menu opens as a sheet split in two: the light half lists the provider’s links, the dark half the caregiver’s; a link on either half also sets the side.',
    probe: [{ home: 'class="sheet-half is-care" data-side-half="caregiver"' }, { home: 'aria-controls="sheet"' }, { css: '.sheet-g{display:grid;grid-template-columns:1fr 1fr' }] },
  { id: 'ap-04', name: 'The bottom split bar', kind: 'mobile',
    what: 'A fixed bar on phones, two halves — For providers, light; For caregivers, dark — with the mark as the pin between them.',
    probe: [{ home: '<nav class="bar" aria-label="Two sides">' }, { home: 'class="bar-pin"' }, { css: 'html[data-side="caregiver"] .bar-pin .mk' }] },
  { id: 'ap-05', name: '⌘K, the verbs', kind: 'navigation',
    what: 'A command palette with Aidepost’s own verbs — Offer to own staff, Post outward, Add a credential date, Export timesheets — plus every page.',
    probe: [{ home: 'data-verb="offer"' }, { home: 'aria-controls="pal"' }, { js: "v === 'export'" }, { js: "e.key.toLowerCase() === 'k'" }] },
  { id: 'ap-06', name: 'Day | Night, the shift badge', kind: 'dark',
    what: 'The light switch is drawn as a shift badge and remembers itself; Night turns the provider side plum-black.',
    probe: [{ home: 'class="badge-t" type="button" data-mode-toggle' }, { css: 'html[data-mode="dark"]{--bg:#1C1620' }, { css: '.badge-t[aria-pressed="true"] .badge-pin' }] },
  { id: 'ap-07', name: 'The real day', kind: 'interaction',
    what: 'The headline says Someone for Saturday night; the script counts to the coming Saturday, lights today on the board, on the phone cards and on the footer rail, and names who is on tonight.',
    probe: [{ home: 'class="hero-live" data-live' }, { home: 'data-tonight' }, { js: '(6 - dow + 7) % 7' }, { js: ".ft-day[data-day], .wkc-d[data-day]" }, { css: '.ft-day[data-today]' }] },
  { id: 'ap-08', name: 'The board, with a face and the hours', kind: 'screen',
    what: 'Every covered cell carries the caregiver’s initials as a disc beside the name, a hover tooltip with the shift and its hours, and a keyboard stop; the row label carries the shift’s hours; the open cell is the one call to action.',
    probe: [{ home: 'class="cell is-covered"' }, { home: 'class="cell-a" aria-hidden="true">AT' }, { home: 'data-tip="A. Tesfaye · Mon day · 06:00 – 14:00"' }, { css: '.cell-a{' }, { css: '.cell[data-tip]::after' }] },
  { id: 'ap-09', name: 'The phone board is seven day cards', kind: 'mobile',
    what: 'Below 640 the table gives way to a snap strip of seven day cards, each with its Day and Night rows, tonight lit, the open shift as an orchid row that opens the claim sheet, and the strip opening on the day with the open shift.',
    probe: [{ home: '<div class="wkc" data-scrollx' }, { home: 'class="wkc-d has-open" data-day="Sat"' }, { home: 'data-cell-proxy' }, { css: '.wkc{display:flex' }, { js: "e.target.closest('[data-cell-proxy]')" }] },
  { id: 'ap-10', name: 'The claim: Saturday night gets covered', kind: 'interaction',
    what: 'Tap the Open cell: a sheet offers the shift to own staff (three names, two markers, nobody removed), posts it outward, R. Alemu claims, you confirm — the cell turns covered and a record line shows you offered inward first.',
    probe: [{ home: 'data-cell-open aria-controls="claim"' }, { home: 'data-claim-act="confirm"' }, { home: 'data-share="https://aidepost.com/#board"' }, { js: "cellT.textContent = 'R. Alemu'" }] },
  { id: 'ap-11', name: 'The notification, from the side, on your side', kind: 'interaction',
    what: 'When the board comes into view a push slides in from the right edge, once per visit. A provider reads the message a manager gets 24 hours out; a caregiver reads the one a relief worker gets when a shift goes outward. Each says what it is in one line, and tapping it opens the thing it names.',
    probe: [{ home: 'id="ntf"' }, { home: 'WH-1: Sat night is still open.' }, { home: 'A shift near you: Sat night · 6.2 mi.' }, { home: 'class="ntf-w s-prov"' }, { js: "sess.get('ap-ntf')" }, { css: '.ntf{left:auto' }, { js: "root.dataset.side === 'caregiver') { const c = document.getElementById('caregivers')" }] },
  { id: 'ap-12', name: 'The annotations: five chips, one sentence', kind: 'screen',
    what: 'Under the desktop board, five numbered chips. Hover, focus or press one and the thing it names — the covered cell, the open cell, the detail card, the two actions, the eligibility list — is ringed on the screen; one panel reads its sentence.',
    probe: [{ home: 'class="an-row" data-scrollx' }, { home: 'class="an-b" type="button" data-spot="2"' }, { home: 'data-an-out' }, { js: "an.addEventListener('pointerover'" }, { css: '.an-out{' }, { css: '.board-phone .is-spot::after{content:attr(data-spot-n)' }] },
  { id: 'ap-13', name: 'The roster builder', kind: 'interaction',
    what: 'A seven-by-two week you can build: every cell cycles A. Tesfaye → J. Ruiz → T. Nguyen → Open, and the coverage count updates.',
    probe: [{ home: 'data-ros data-names="A. Tesfaye|J. Ruiz|T. Nguyen"' }, { home: 'class="ros-c is-open"' }, { js: '(Number(b.dataset.who) + 1) % 4' }] },
  { id: 'ap-14', name: 'The life of one credential', kind: 'screen',
    what: 'J. Ruiz’s First Aid card beside a track of five stations — recorded, thirty days, seven days, expired, renewed — each with the badge set’s glyph; the station the card has reached lights and the card wears its state. Round 4: the rail and the slider panel became one instrument.',
    probe: [{ home: 'class="cl" data-tl data-state="current"' }, { home: 'class="cl-s is-expired" role="listitem" data-cl-s="3"' }, { home: 'data-cl-s="4"' }, { css: '.cl-s[data-on] .cl-dot{' }] },
  { id: 'ap-15', name: 'Drag the days, record the renewal', kind: 'interaction',
    what: 'The slider walks the card through current, the thirty- and seven-day notices and the day itself on evenly spaced stations; past the day a button records the renewal — a new row, the old one kept as history. Nothing on the track blocks an assignment.',
    probe: [{ home: 'data-tl-in' }, { home: 'data-tl-card data-state="current"' }, { js: "days < 0 ? 'expired' : days <= 7 ? 'notice7'" }, { home: 'data-cl-renew hidden' }, { css: '.cl-card[data-state="expired"]' }] },
  { id: 'ap-16', name: 'The timesheet, weekly flag only', kind: 'interaction',
    what: 'Seven day bars you can toggle; the weekly total recomputes and the forty-hour flag appears or goes — weekly, never daily — with an Export CSV that says hours, never pay.',
    probe: [{ home: 'class="ts-d" type="button" data-h="8" aria-pressed="true"' }, { home: 'data-ts-export' }, { js: 'weekly flag, never daily' }, { css: '.ts-f.is-over' }] },
  { id: 'ap-17', name: 'Clock in at the house', kind: 'interaction',
    what: 'Press Clock in and a ring closes around the house pin, stamped with the live time and WH-1; press again to clock out.',
    probe: [{ home: 'data-ck-btn' }, { home: 'class="ck-arc"' }, { js: 'Clocked in at ${time()} · WH-1' }, { css: '.ck.is-in .ck-arc{stroke-dashoffset:0' }] },
  { id: 'ap-18', name: 'The distance slider, on the page and in the phone', kind: 'screen',
    what: 'On the dark half, a slider from 2 to 25 miles filters the three offers on the page and dims the same rows inside the caregiver phone beside it.',
    probe: [{ home: 'data-dist-in' }, { home: 'class="offer" data-mi="4.2"' }, { js: "rows[i].classList.toggle('is-far', far)" }, { css: '.phone .row-a.is-far' }] },
  { id: 'ap-19', name: 'Does this shift fit you?', kind: 'interaction',
    what: 'Four taps — how far, awake overnight, medication-certified, free Saturday — and one shift card answers: this fits, or close and what is missing, or not this one. It never blocks, because the product never does: a missing credential shows beside a name and the house decides.',
    probe: [{ home: 'data-fq-box' }, { home: 'data-fq="meds"' }, { home: 'data-fq-card data-fit="yes"' }, { js: "near.push('it asks for medication-certified" }, { css: '.fq-card[data-fit="near"]' }, { html: 'Does this shift fit you?' }] },
  { id: 'ap-20', name: 'The wallet, as a deck', kind: 'screen',
    what: 'Four credential cards stacked like the cards in a purse — each shows its edge: its own glyph, its name, its date; the one that needs her is in front, and a tap brings any card forward with its issuer and who saw it.',
    probe: [{ home: 'class="wcard is-open" role="listitem" data-kind="firstaid" data-front' }, { home: 'American Heart Association' }, { home: 'Seen by M. Kebede · 12 Sep' }, { css: '.wcard[data-front]{' }, { js: "c.toggleAttribute('data-front', on)" }] },
  { id: 'ap-21', name: 'Roles as flip cards, with their glyphs', kind: 'interaction',
    what: 'Five roles, each a card that turns over to show what that role may do; each carries a glyph — house, clipboard, person, phone, distance — and two of them are drawn on the dark side.',
    probe: [{ home: '<details class="flip ' }, { home: 'class="flip-b"' }, { css: '.flip[open]{transform:rotateY(180deg)' }, { css: '.role-n{display:inline-flex' }] },
  { id: 'ap-22', name: 'Set your houses, see your month', kind: 'interaction',
    what: 'Providers | Caregivers on the pricing block: a houses stepper prices Pro ($29) and Scale ($59) a house a month for the count you set and marks the plan that fits; the job post is the third card at $25 a post, the trial one line; the caregiver side is $0, for ever.',
    probe: [{ home: 'class="pc pc-ap" data-houses data-start="2"' }, { home: 'data-per="29"' }, { home: 'data-fit="1-3"' }, { home: '<b>$25</b><small>/ post</small>' }, { home: '$0<small> for ever</small>' }, { js: "el.toggleAttribute('data-fits'" }] },
  { id: 'ap-23', name: 'Keyboard: 1, 2, ⌘K, ?, Esc — docked beside the fab', kind: 'a11y',
    what: '1 and 2 switch sides, ⌘K opens the verbs, ? opens a shortcut card, Escape closes whatever is open. The Keys button is docked beside the floating write-to-us.',
    probe: [{ home: 'aria-controls="keys"' }, { home: 'data-fab-side' }, { home: '<kbd>?</kbd>' }, { js: "e.key === '1'" }, { js: "e.key === '?'" }] },
  { id: 'ap-24', name: 'The boundary follows the pointer', kind: 'motion',
    what: 'The two doors share one band; the light/dark boundary eases toward the cursor on a desktop and splits 50/50 on touch.',
    probe: [{ home: 'data-doors style="--x:50%"' }, { css: 'clip-path:polygon(var(--x) 0' }, { js: "d.style.setProperty('--x'" }, { js: 'calm.matches ||' }] },
  { id: 'ap-25', name: 'The phones travel with the reader', kind: 'motion',
    what: 'The hero device and the section phones carry data-scroll-p; the shared scroll driver hands them --sp and the sheet turns it into a slow lift, so the screens move with the page rather than sit on it.',
    probe: [{ home: 'class="hero-dw" aria-hidden="true" data-scroll-p' }, { home: 'class="hrs-v" data-scroll-p' }, { css: 'var(--sp,.5) - .5' }] },
  { id: 'ap-26', name: 'Print the roster', kind: 'print',
    what: 'Print this week on the board, or Print the roster in the footer, prints the week board — and nothing else on the page.',
    probe: [{ home: 'class="btn sm ft-print" type="button" data-print' }, { css: '@media print' }, { css: 'main>:not(.hero):not(#board){display:none' }] },
  { id: 'ap-27', name: 'Two doors at depth: /providers and /caregivers', kind: 'page',
    what: 'The provider page walks four screens — board, credentials, hours, hiring — each with its flow told step by step; the caregiver page is dark end to end, with the fit quiz and the rules that protect a worker.',
    probe: [{ route: 'providers' }, { route: 'caregivers' }, { html: 'class="crl-a" href="#hiring"' }, { html: 'class="prot-g"' }] },
  { id: 'ap-28', name: 'Write to a person, with topics', kind: 'page',
    what: 'The contact page carries the kit’s form with Aidepost’s topics and two addresses with a copy button each — and copying an address also opens the mail app.',
    probe: [{ route: 'contact' }, { html: '<option value="I’m a caregiver">' }, { html: 'id="contactform"' }, { route: 'caregivers' }, { html: 'mailto:caregiver@aidepost.com' }] },
  { id: 'ap-29', name: 'Reach a person: three steps after the questions', kind: 'page',
    what: 'The questions end in a conversation: write, a person answers within a working day, see it run in twenty minutes — with the page’s own address and the form one tap away, on the front page and on /pricing.',
    probe: [{ home: 'class="reach" id="reach"' }, { home: 'class="reach-s"' }, { html: 'Pricing — Aidepost' }] },
  { id: 'ap-30', name: 'The footer: an address, three groups and the name', kind: 'footer',
    what: 'The page’s own address with copy-and-open-mail, Product, Caregivers and Company with room to breathe, tonight lit on a small week with the roster to print, the byline and the legal line in the bottom bar, and Aidepost drawn across the foot.',
    probe: [{ home: 'class="fsh ft" id="foot"' }, { home: '<ol class="ft-week"' }, { home: 'class="ft-day" data-day="Thu"' }, { home: 'data-clock="day"' }, { home: 'data-copy="shifts@aidepost.com"' }, { home: 'class="fsh-wm"' }, { home: 'By Providerhub' }] },
  { id: 'ap-31', name: 'Next, floating', kind: 'navigation',
    what: 'Every route ends with a small floating “Next · X” at the bottom-left that appears once the reader is well into the page — the route after this one in the ring — instead of a two-card block.',
    probe: [{ home: 'class="nxt ' }, { home: 'data-next aria-label="Next page: For providers' }, { html: 'data-next aria-label="Next page: Privacy' }] },
  { id: 'ap-32', name: 'Social, in the bottom bar', kind: 'social',
    what: 'Eight platforms as a quiet row of glyphs in the footer’s bottom bar, beside the byline and the legal line.',
    probe: [{ home: 'class="soc fsh-soc"' }, { css: '.fsh-soc .soc-i{' }] },
  { id: 'ap-33', name: 'All five screens, in one rail', kind: 'screen',
    what: '/screens carries every real Aidepost screen in one full-bleed rail that snaps, drags, takes the arrow keys and announces where it is.',
    probe: [{ route: 'screens' }, { html: 'class="fs-rail" id="strip-rail"' }, { html: 'id="strip-caregiver"' }, { html: 'What this proves' }] },
  { id: 'ap-34', name: 'The hero device takes the side', kind: 'interaction',
    what: 'On /screens the hero device is a real tablist — I run a house | I’m a caregiver — wired to the site-wide switch in both directions.',
    probe: [{ html: 'id="sw-sides"' }, { html: 'aria-controls="sw-sides-p1"' }, { js: "getElementById('sw-sides')" }, { js: "b.dataset.swTo === '1'" }] },
  { id: 'ap-35', name: 'Five pins on the hiring screen', kind: 'screen',
    what: 'The desktop hiring shell carries five numbered callouts; point at one, or reach its sentence with a keyboard, and it lights the element it quotes.',
    probe: [{ html: 'id="cal-hire"' }, { html: 'data-sel=".page-side .tile-a"' }, { html: 'class="cal-i" tabindex="0"' }, { css: '.cal-pin{background:var(--orchid)' }] },
  { id: 'ap-36', name: 'One chapter rail on every route', kind: 'navigation',
    what: 'One rail replaces the page index and the screens jump that stacked above it: horizontal, following the reader, each chapter with its badge glyph, a dot where there is something to try, a hairline that fills as you read, and the five screens as its last link.',
    probe: [{ home: '<nav class="crl" aria-label="On this page" data-crl>' }, { home: 'class="crl-a" href="#credentials"' }, { home: 'class="crl-x" href="/screens"' }, { css: '.crl-a[aria-current]{' }, { js: "new CustomEvent('pho:chapter'" }] },
  { id: 'ap-37', name: 'Where you are, in the header', kind: 'mobile',
    what: 'Below 900 the header names the route under the wordmark, because a phone header has no section rail to infer it from.',
    probe: [{ home: 'class="hd-where" data-where>Both sides' }, { html: 'class="hd-where" data-where>The screens' }, { css: '.hd-where{display:flex;align-items:center' }] },
  { id: 'ap-38', name: 'Every jump says where you landed', kind: 'navigation',
    what: 'Any in-page link lands its section just under the header and the rail, underlines the heading for a moment, moves focus to it and names the place in a small tag — “You are here · Credentials” — so a click never ends in a silent nudge.',
    probe: [{ js: "hereEl.className = 'here'" }, { js: "head.setAttribute('data-here-h'" }, { css: '[data-here-h]{' }, { css: '.here.is-on{' }] },
  { id: 'ap-39', name: 'Every field on a shift, and the one that is not', kind: 'page',
    what: 'The nine fields a shift record carries, and then the field that is absent, with the schema check that asserts it.',
    probe: [{ route: 'screens' }, { html: 'class="schm-f"' }, { html: 'The schema check asserts it.' }] },
  { id: 'ap-40', name: 'The first ten minutes, ticked off', kind: 'interaction',
    what: 'The four things you do on day one, as checkboxes you can tick against the rail — :checked strikes the line through, no script.',
    probe: [{ html: 'class="ft10-x" type="checkbox" id="ft10-3"' }, { css: '.ft10-x:checked' }] },
  { id: 'ap-41', name: 'The contact form arrives on your side', kind: 'interaction',
    what: 'The topic select follows the side you are on and stops following the moment you touch it; the form’s address follows the topic.',
    probe: [{ js: '#contactform select[name="topic"]' }, { html: '<option value="I’m a caregiver">' }, { route: 'contact' }] },
  { id: 'ap-42', name: 'The lit chapter stays in view', kind: 'mobile',
    what: 'The rail keeps the chapter you are in centred by scrolling itself, never the page; a phone shows 03 / 12 beside it.',
    probe: [{ js: 'list.scrollTo({ left: Math.max(0, left)' }, { home: 'data-crl-n' }] },
  { id: 'ap-43', name: 'The swipe strip reports its own edges', kind: 'mobile',
    what: 'Between 641 and 900 the desktop-board strip holds a 768px board in a narrower gutter; it fades the side that still has board behind it and lifts the fade on the side you have reached. Below 640 the strip gives way to the phone board.',
    probe: [{ js: "s.dataset.sx = max <= 2 ? 'none'" }, { js: "matchMedia('(max-width: 1100px)')" }, { css: '.shell[data-sx="mid"]' }] },
  { id: 'ap-44', name: 'The four words, and no fifth colour', kind: 'page',
    what: 'The four state words this product owns — covered, open, pending, expired — with what each one means.',
    probe: [{ html: 'class="stl-i is-expired"' }, { css: '.stl-i.is-expired .stl-d' }] },
  { id: 'ap-45', name: 'The board on a phone is a phone board', kind: 'mobile',
    what: 'Below 640 the desktop mock gives way to the same screen drawn for a thumb: the week as a grid that fits the gutter, Saturday night open in the accent, the shift card with its two actions — which open the claim sheet and run it, inward first — and the eligibility list. The five chips ring the same five things on it. On /providers the same board carries the two actions as a line, because that page has no claim sheet.',
    probe: [{ home: 'class="board-phone"' }, { home: 'class="pb" data-pboard' }, { home: 'class="pb-c is-open" data-spot-el="2"' }, { home: 'data-claim-go="post"' }, { css: '#board .board-desk{display:none}' }, { css: '#board .board-phone{display:block}' }, { js: '[data-spot-el="${n}"]' }, { html: 'class="pb-next" data-spot-el="4"' }] },
];

export default FEATURES;
