// binderkit.com — the fifty, each one checked against the built bytes.
//
// 01–25 are the binder itself: the index tabs, the control numbers, the
// contents sheet, the planner and the print. 26–50 are the working demo and
// the case around it: the five real screens as plates, the switcher, the
// annotated editor, the boundary the product refuses to cross, and the state
// of the work stated plainly.
//
// A probe is chosen so that REMOVING THE FEATURE MAKES THE PROBE FAIL. That
// rules out probing anything in a shared file: css/instruments-extra.css and
// js/site.js carry the mechanism for the rail, the tablist and the pins and
// would still be there with every one of them deleted from this site. Every
// `css` probe below is a rule in css/pages/binderkit.css and every `js` probe
// is a line in js/pages/binderkit.js.
export const FEATURES = [
  { id: 'bk-01', name: 'Index-tab navigation', kind: 'navigation',
    what: 'The sections are a column of binder index tabs fixed to the right edge; the tab for the section in view is pulled out and inked, and hovering a tab slides its label out.',
    probe: [{ home: 'class="tabs" aria-label="Sections" data-spy' }, { css: '.dtab[aria-current="true"]' }, { home: 'class="dtab-l">Plan</span><span class="dtab-n">' }] },
  { id: 'bk-02', name: 'Running control number', kind: 'header',
    what: 'The top rule carries BK-LP-nn, the control number of the section you are reading, and it changes as you scroll.',
    probe: [{ home: 'id="run-ctl"' }, { js: "$('#run-ctl')" }, { home: 'data-ctl="BK-LP-02"' }] },
  { id: 'bk-03', name: 'The contents sheet', kind: 'header',
    what: 'A Contents button in the rule opens a table of contents — every chapter and this page’s sections with dotted leaders — which is also the phone menu; it locks scroll and closes on Escape or any link.',
    probe: [{ home: 'aria-controls="contents" data-lock' }, { home: 'class="toc-sheet" id="contents"' }] },
  { id: 'bk-04', name: 'Keys and the ⌘K palette', kind: 'navigation',
    what: '← and → move between tabs, p prints, l switches the lamp, ? shows the card, and ⌘K opens a palette of the product’s own verbs — Re-plan, Print the contents page, Add a note, Compare versions — plus every section and chapter.',
    probe: [{ home: 'id="palette"' }, { home: 'id="keys"' }, { js: "e.key === 'ArrowRight'" }, { js: "e.key.toLowerCase() === 'k'" }, { home: 'data-verb="compare"' }] },
  { id: 'bk-05', name: 'A contents page for a footer', kind: 'footer',
    what: 'The footer is a real contents page: every section and every chapter as a numbered line with dotted leaders running to its control number.',
    probe: [{ home: 'class="foot-h">Contents' }, { css: '.toc-l{' }, { home: 'class="toc toc-ch"' }, { home: 'class="toc-n">BK-LP-11' }] },
  { id: 'bk-06', name: 'The colophon', kind: 'footer',
    what: 'The mark sits centred above the typefaces, the control number of this build and a live “printed <date>” that the page fills in from your clock.',
    probe: [{ home: 'class="colophon"' }, { home: 'data-clock="date"' }, { home: 'class="colo-ctl"' }] },
  { id: 'bk-07', name: 'Footer stamps', kind: 'footer',
    what: 'plan@binderkit.com as a punched stamp that mails, a stamp that copies the address, a stamp that shares the page and a stamp that prints — all beside the eight social stamps.',
    probe: [{ home: 'class="stamps-row"' }, { home: 'data-copied="Address copied"' }, { home: 'mailto:plan@binderkit.com' }, { home: 'class="stamp" type="button" data-share' }] },
  { id: 'bk-08', name: 'The planner, live and deterministic', kind: 'interaction',
    what: 'Pick a track, answer the five questions with real controls, and the plan regenerates in the page — which binders, why, how many tabs and dividers — the same answers always giving the same plan; Reset restores the demonstration, and a Copy button carries the plan as text.',
    probe: [{ home: 'id="planner"' }, { home: 'id="bk-plan-data"' }, { js: 'function computePlan(D, a)' }, { js: 'data-plan-reset' }, { home: 'data-plan-copy' }, { home: 'name="track" value="AFH-DD"' }] },
  { id: 'bk-09', name: 'The sheet fills from the plan', kind: 'screen',
    what: 'Every contents page on the site — the one on the desk in the hero and the annotated one in The page — redraws its rows, version and control number from the plan as you answer.',
    probe: [{ home: 'data-sheet-rows' }, { js: 'data-sheet-control' }, { home: 'data-sheet-printed' }] },
  { id: 'bk-10', name: 'Seven chapters', kind: 'page',
    what: 'The screens, The plan, The library, Pricing, About and Contact are chapters of the same binder, each with its own control prefix, index tabs and contents page.',
    probe: [{ route: 'plan' }, { route: 'library' }, { route: 'pricing' }, { route: 'about' }, { route: 'contact' }, { route: 'screens' }, { html: 'data-ctl="BK-LB-01"' }] },
  { id: 'bk-11', name: 'Evidence legend', kind: 'interaction',
    what: 'Three toggles — verified, derived, open — filter which rows of the sheet show, with a running count; a struck-through toggle is a hidden tag.',
    probe: [{ home: 'data-ev-toggle="derived"' }, { js: 'evToggle' }, { home: 'data-legend-count' }] },
  { id: 'bk-12', name: 'Citation popover', kind: 'interaction',
    what: 'Hover or tap any OAR citation to see, in a paper popover, which chapter and section it is and its evidence line; without JavaScript the same link jumps to the glossary of citations on the page.',
    probe: [{ home: 'class="cite" href="#cites"' }, { home: 'id="cites"' }, { js: "className = 'pop'" }] },
  { id: 'bk-13', name: 'Version diff', kind: 'interaction',
    what: 'A v1 / v2 switch on the versions table: v1 hides the current row and strikes the added tab; v2 shows the added and moved rows with the periwinkle re-plan banner and the superseded version kept.',
    probe: [{ home: 'data-vtable' }, { css: '[data-v="1"] tr[data-change="Current"]' }, { js: 'data-vtable' }, { home: 'data-v-banner' }] },
  { id: 'bk-14', name: 'Page turn', kind: 'interaction',
    what: 'Turn the page flips the sheet in three dimensions to show the tab dividers on its back; it turns back on a second press and before printing.',
    probe: [{ home: 'data-turn' }, { css: 'rotateY(180deg)' }, { js: "classList.toggle('is-turned'" }, { home: 'class="divset"' }] },
  { id: 'bk-15', name: 'Hold it at true size', kind: 'screen',
    what: 'A button renders the sheet at exactly 8.5 by 11 inches — 816 by 1056 pixels — in a modal with an inch ruler along the top and side; Escape closes it.',
    probe: [{ home: 'id="lens"' }, { css: '8.5in' }, { js: 'data-lens-sheet' }, { home: 'class="ruler ruler-x"' }] },
  { id: 'bk-16', name: 'Print the contents page', kind: 'print',
    what: 'Print, p, the palette or the foot bar prints only the sheet on a letter page, with the control number in its footer and the mark as the printer’s mark at the bottom.',
    probe: [{ home: 'data-print-sheet' }, { css: '@page{size:letter' }, { css: '.cp-mark{display:flex' }, { home: 'class="cp-mark"' }] },
  { id: 'bk-17', name: 'The tab strip on phones', kind: 'mobile',
    what: 'Under the top rule the index tabs become a scroll-snapping strip — 1 Proof · 2 Screens · 3 Plan … — that follows the section in view, with the early-access button at its end.',
    probe: [{ css: 'scroll-snap-type:x mandatory' }, { home: 'class="tabs-cta"' }, { js: 'list.scrollTo(' }] },
  { id: 'bk-18', name: 'The foot bar on phones', kind: 'mobile',
    what: 'A slim fixed bar above the safe area carries Print, the page number “p. n / N” driven by scroll, and Join — the two primary actions under a thumb.',
    probe: [{ home: 'class="footbar"' }, { home: 'data-page-n' }, { js: 'data-page-n' }, { css: 'env(safe-area-inset-bottom)' }] },
  { id: 'bk-19', name: 'The magnifier on phones', kind: 'mobile',
    what: 'A contents page cannot be read at 390 pixels, so on a phone a Magnify stamp — or a tap on the sheet — opens it at true size in a pannable view.',
    probe: [{ home: 'class="sheet-tap"' }, { js: "'.cp.is-hero, .cp.is-page'" }, { home: 'class="lens-scroll" data-scrollx' }] },
  { id: 'bk-20', name: 'The lamp', kind: 'dark',
    what: 'Dark mode is a desk lamp: the paper goes warm under a pool of light and the ink stays black; the choice is remembered, and the lamp icon draws its light when it is on.',
    probe: [{ home: 'data-mode-toggle' }, { css: 'html[data-mode="dark"]{--bg:#F3EBDA' }, { home: 'class="lamp-on"' }, { css: 'mix-blend-mode:multiply' }] },
  { id: 'bk-21', name: 'Ink that draws itself', kind: 'motion',
    what: 'The three forbidden words are struck through with a periwinkle rule that draws as they scroll in, and the six rules of holding nothing get a tick that fills as each one arrives.',
    probe: [{ home: 'class="strike"' }, { home: 'data-ledger' }, { css: 'stroke-dashoffset:0' }, { js: 'data-ledger' }] },
  { id: 'bk-22', name: 'Subscription or single purchase', kind: 'interaction',
    what: 'A switch on the pricing rows changes the wording between subscription and single purchase — open item #9 — and never the number, which stays Early access.',
    probe: [{ home: 'data-sell="once"' }, { js: 'data-sell-note' }, { html: 'data-once="' }] },
  { id: 'bk-23', name: 'Questions with their own addresses', kind: 'interaction',
    what: 'Each question is a numbered disclosure with an address of its own; a link under the answer copies it, and arriving at that address opens the question.',
    probe: [{ home: 'class="faq-link"' }, { re: 'href="#q-1"' }, { js: 'details[id]' }, { home: 'data-copied="Link to this question copied"' }] },
  { id: 'bk-24', name: 'Write to a person', kind: 'email',
    what: 'The contact chapter carries the shared contact form with Binderkit’s own topics — Question, Early access, Which track?, Pricing, Press, Something else — and plan@binderkit.com beside it.',
    probe: [{ route: 'contact' }, { html: 'id="contactform"' }, { html: '<option value="Which track?">' }, { html: 'data-ctl="BK-CT-02"' }] },
  { id: 'bk-25', name: 'Social stamps', kind: 'social',
    what: 'All eight platforms as square punched stamps that ink on hover; on the contact chapter they carry their handles.',
    probe: [{ home: 'class="soc stamps"' }, { css: '.stamps .soc-i{' }, { re: 'class="soc-i" data-net="bluesky"' }, { html: 'class="soc stamps is-text"' }] },

  /* ══ THE WORKING DEMO ══════════════════════════════════════════════ */
  { id: 'bk-26', name: 'The plate section', kind: 'screen',
    what: 'A chapter of its own, /screens, holds all five real product screens as a full-bleed strip of plates at the size they ship, snapped, draggable and walkable with the arrow keys — the link a partner clicks when they want the whole product rather than the argument about it.',
    probe: [{ route: 'screens' }, { html: 'data-strip="binderkit"' }, { html: 'id="plates-rail"' }, { html: 'id="plates-editor"' }] },
  { id: 'bk-27', name: 'What each plate proves', kind: 'screen',
    what: 'Every plate carries an ordinal, the tab it is filed under, a caption in the product’s own words and a “What this proves” line — so a screenshot makes a claim that can be checked rather than just looking like software.',
    probe: [{ html: 'class="fs-pl">What this proves' }, { html: 'The identity line is blank and filled in by hand.' }, { html: 'A print that fails consumes no control number. Any past control number reproduces the identical artefact.' }] },
  { id: 'bk-28', name: 'Jump to a plate', kind: 'navigation',
    what: 'The plate strip carries an index of real anchors above it — 01 Plan · 02 Binders · 03 Editing · 04 Versions · 05 Print — which marks the plate in view and lands a single screen sideways without moving the page.',
    probe: [{ html: 'class="fs-jump"' }, { html: 'aria-label="Jump to a plate"' }, { html: 'href="#plates-versions"' }] },
  { id: 'bk-29', name: 'Every plate has an address', kind: 'interaction',
    what: 'A button inside each plate’s caption copies the deep link to that one screen, so a single plate can be sent to somebody without the rest of the page around it.',
    probe: [{ html: 'data-copy="https://binderkit.com/screens#plates-print"' }, { html: 'data-copied="Link to this plate copied"' }, { css: '.plate-a{' }] },
  { id: 'bk-30', name: 'The index tabs switch the screen', kind: 'screen',
    what: 'On the front page the two halves of the product — the plan going in, the binder coming out — are one device whose screen changes when you press its index tab, with no layout shift at all: the stage keeps the height of the taller screen.',
    probe: [{ home: 'id="sw-screens"' }, { home: 'role="tablist"' }, { home: 'data-sw-to="1"' }, { home: 'class="swx-stage"' }] },
  { id: 'bk-31', name: 'The register of plates', kind: 'page',
    what: 'The front page prints the register a printed book puts before its plate section: five numbered rows, each naming the screen, what it shows, the one thing it is evidence for, and the address of its plate.',
    probe: [{ home: 'class="preg"' }, { home: 'class="preg-i" data-plate="print"' }, { home: 'class="preg-pl">What this proves' }, { css: '.preg-i{' }] },
  { id: 'bk-32', name: 'Numbered callouts on the guarded editor', kind: 'screen',
    what: 'Four numbered pins sit on the desktop editor, each quoting one real element of it; pointing at a pin, or tapping its sentence, lights the pin, the row and the element inside the screen. Below 900px the editor is drawn without the pins — css/pages/binderkit.css hides them — so on a phone the four sentences are the whole of it, and none of them takes keyboard focus.',
    probe: [{ home: 'id="cal-editor"' }, { home: 'data-callouts' }, { home: 'class="cal-pin" data-cal="1"' }, { home: 'class="cal-list"' }] },
  { id: 'bk-33', name: 'The contents sheet says where you are', kind: 'mobile',
    what: 'The sheet is the phone menu and it opens from any scroll position, so the section you are in is marked in it — a caret, a bold title and the control number inked — which is how a phone reader knows where they are without scrolling back.',
    probe: [{ home: 'class="toc toc-in-ch" data-spy' }, { css: '.toc-in-ch a[aria-current="true"]' }, { html: 'class="toc toc-in-ch" data-spy' }] },
  { id: 'bk-34', name: 'Leaf back, leaf forward', kind: 'navigation',
    what: 'Every chapter ends with the page before it and the page after it, each with its title and its control prefix — two real links, no script, and the first and last chapter simply lose one side.',
    probe: [{ home: 'class="pager"' }, { html: 'rel="prev"' }, { html: 'class="pager-t">The plan' }, { css: '.pager-a{' }] },
  { id: 'bk-35', name: 'The control number is the address', kind: 'interaction',
    what: 'A control number is an address in a binder, so here it is one on the web too: the stamp in every section’s margin is a button that copies the deep link to that section.',
    probe: [{ home: 'class="ctl" type="button"' }, { home: 'data-copy="https://binderkit.com/#page"' }, { home: 'data-copied="Link to this section copied"' }, { css: '.ctl-c{' }] },
  { id: 'bk-36', name: 'The palette reaches every section of every chapter', kind: 'navigation',
    what: '⌘K — Ctrl-K on a keyboard without a command key — finds any section of any chapter by its name or by its control number — type “guardrails”, “BK-LB” or “never” — and goes straight there from whichever page you are on. It is a keyboard affordance and nothing on the page opens it: a phone reader crosses chapters through the contents sheet, which lists every one.',
    probe: [{ home: 'data-verb="open:/plan#guardrails"' }, { home: 'data-verb="open:/library#never"' }, { js: "verb.startsWith('open:')" }] },
  { id: 'bk-37', name: 'The state of the work, stated plainly', kind: 'page',
    what: 'A ledger of what is built and what is not: this page live, the product drafted with no repository, the four libraries not written, the reading not started, the price not decided — each row carrying its own word rather than a colour.',
    probe: [{ home: 'id="state"' }, { home: 'data-state-row="libraries"' }, { home: 'class="stat-l is-none">not written' }, { css: '.stat-l{' }] },
  { id: 'bk-38', name: 'Counts, not claims', kind: 'page',
    what: 'Six numbers, read from the specification: four libraries needed, none written, thirty-two items observed, ninety-four derived, ninety-nine citations recorded and nought verified — with the note that the thirty-two is one home’s shelf, not a state requirement.',
    probe: [{ home: 'class="counts"' }, { home: 'data-count="verified">0' }, { home: 'data-count="recorded">99' }] },
  { id: 'bk-39', name: 'The four words this product owns', kind: 'interaction',
    what: 'Verified, derived, unverified and superseded, drawn as the evidence tags they are on the printed page, each with the sentence that defines it — the vocabulary every item on every artefact is stamped with.',
    probe: [{ home: 'class="tag-g words is-4"' }, { home: 'data-word="superseded"' }, { home: 'class="ev is-unverified"' }] },
  { id: 'bk-40', name: 'What it refuses to do', kind: 'page',
    what: 'The boundary, in two columns: three capabilities that belong to a sibling product and are named with it, and five the family refuses outright — a product that states what it will not do is a product with a thesis.',
    probe: [{ home: 'class="bd-g"' }, { home: 'data-next="careshop"' }, { home: 'class="bd-c bd-never"' }, { css: '.bd-g{' }] },
  { id: 'bk-41', name: 'The boundary test, run on your idea', kind: 'interaction',
    what: 'The four questions the team puts every request through, as four real checkboxes: tick what a capability does and the page names the room it belongs in. No script — it is a :has() rule, so it works with scripting off.',
    probe: [{ home: 'data-bt="store"' }, { home: 'data-bt-out' }, { home: 'data-bt-a="finding"' }, { css: '.bt:has(#bt-store:checked)' }] },
  { id: 'bk-42', name: 'The graduation path', kind: 'page',
    what: 'Where each part of a Binderkit plan lands inside Provider Hub Oregon — plans and versions into the Digital Binder, libraries into M06 and M19 — with the family rule beside it: every mini graduates by export into import, and her data is already in the platform’s shape.',
    probe: [{ home: 'class="grad"' }, { home: 'data-grad="M06"' }, { home: 'class="toc is-ladder"' }] },
  { id: 'bk-43', name: 'The family band', kind: 'page',
    what: 'The other three minis and the platform, each with its drawn mark, what it owns, its own honest status and a live link to it — one house, four rooms, one ladder, with this room underlined.',
    probe: [{ home: 'class="rooms"' }, { home: 'data-fam="cohort"' }, { home: 'href="https://careshop.app"' }, { home: 'class="room-m"' }] },
  { id: 'bk-44', name: 'The case, in three', kind: 'page',
    what: 'Three numbered proofs at the top of the page: it holds nothing about anyone, it is deterministic and you can check it here, and every item prints its authority or says it has none.',
    probe: [{ home: 'id="why"' }, { home: 'class="art-g proof-g"' }, { home: 'data-proof="3"' }, { css: '.art-g.proof-g{' }] },
  { id: 'bk-45', name: 'Determinism, checked in the page', kind: 'interaction',
    what: 'A button runs the planner’s rule twice over the answers you have given and compares the two results character for character, reporting the length and the verdict — the investment claim, made checkable rather than asserted.',
    probe: [{ home: 'data-determinism' }, { home: 'data-det-out' }, { js: 'planTwice' }, { js: 'character for character' }] },
  { id: 'bk-46', name: 'The three guardrails, played', kind: 'interaction',
    what: 'Three buttons attempt the three edits the product refuses — remove a required item, move a staff record into a resident binder, split a tab — and each prints the refusal verbatim, with the guardrail that answered and the alternative it is required to offer.',
    probe: [{ home: 'data-guard-try="coverage"' }, { home: 'data-gname="Cohesion"' }, { home: 'class="tryg-o"' }, { js: 'data-guard-try' }] },
  { id: 'bk-47', name: 'The control number, taken apart', kind: 'page',
    what: 'The four parts of every printed control number — facility code, binder, plan version, print sequence — each named and explained, because two contents pages on a desk are only telling you apart by that number.',
    probe: [{ home: 'class="ctlx"' }, { home: 'data-part="sequence"' }, { css: '.ctlx dt code{' }] },
  { id: 'bk-48', name: 'Nine tables, seven platform, nought about a resident', kind: 'page',
    what: 'What the product holds, counted: nine organisational tables, seven platform tables carrying staff account information, and nought holding anything about a resident — the wedge, as a number rather than a promise.',
    probe: [{ home: 'class="tbls"' }, { home: 'data-tbl="phi">0' }, { home: 'data-tbl="product">9' }] },
  { id: 'bk-49', name: 'Four notifications, and there is no fifth', kind: 'page',
    what: 'The whole notification catalogue, closed: a new plan version, a library update, a trial ending, an export to download — and no push notification at all, because nothing in this product is urgent enough to interrupt anyone.',
    probe: [{ home: 'class="notif"' }, { home: 'data-notif="library"' }, { home: 'no push notification at all' }] },
  { id: 'bk-50', name: 'Where you are, in the foot bar', kind: 'mobile',
    what: 'The phone foot bar’s page counter carries the name of the section you are in as well as its number, because on a page eight thousand pixels long a number is a progress bar and a name is a location.',
    probe: [{ home: 'data-page-name' }, { js: 'data-page-name' }, { css: '.fb-w{' }] },
];
