// binderkit.com — the features, each one checked against the built bytes.
//
// 01–25 are the binder itself: the index tabs, the control numbers, the
// contents sheet, the planner and the print. 26 on are the working demo and
// the case around it: the five real screens, the switcher, the annotated
// editor, the rules in plain words, the reach-us block and the real prices.
//
// A probe is chosen so that REMOVING THE FEATURE MAKES THE PROBE FAIL. That
// rules out probing anything in a shared file: every `css` probe below is a
// rule in css/pages/binderkit.css and every `js` probe is a line in
// js/pages/binderkit.js.
export const FEATURES = [
  { id: 'bk-01', name: 'Index-tab navigation', kind: 'navigation',
    what: 'The sections are a column of binder index tabs fixed to the right edge, each printed with its word and its number; the tab for the section in view is pulled out and inked.',
    probe: [{ home: 'class="tabs" aria-label="Sections" data-spy' }, { css: '.dtab[aria-current="true"]' }, { home: 'class="dtab-l">Plan</span><span class="dtab-n">' }, { css: '.dtab{display:grid;grid-template-rows' }] },
  { id: 'bk-02', name: 'Running control number', kind: 'header',
    what: 'The top rule carries BK-LP-nn, the control number of the section you are reading, and it changes as you scroll.',
    probe: [{ home: 'id="run-ctl"' }, { js: "$('#run-ctl')" }, { home: 'data-ctl="BK-LP-02"' }] },
  { id: 'bk-03', name: 'The contents sheet', kind: 'header',
    what: 'A Contents button in the rule opens a table of contents — every chapter and this page’s sections with dotted leaders — which is also the phone menu; it locks scroll and closes on Escape or any link.',
    probe: [{ home: 'aria-controls="contents" data-lock' }, { home: 'class="toc-sheet" id="contents"' }] },
  { id: 'bk-04', name: 'Keys and the ⌘K palette', kind: 'navigation',
    what: '← and → move between tabs, p prints, l switches the lamp, ? shows the card, and ⌘K opens a palette of the product’s own verbs plus every section and chapter.',
    probe: [{ home: 'id="palette"' }, { home: 'id="keys"' }, { js: "e.key === 'ArrowRight'" }, { js: "e.key.toLowerCase() === 'k'" }, { home: 'data-verb="compare"' }] },
  { id: 'bk-05', name: 'The chapters, in the footer', kind: 'footer',
    what: 'Round 4: the shared footer shell in the binder’s ink — the eight chapters as two groups, the binder and the company, with room to breathe, the byline and the legal line, and Binderkit drawn across the foot.',
    probe: [{ home: 'class="fsh foot" id="foot"' }, { home: 'aria-label="The binder"' }, { home: 'class="fsh-wm"' }] },
  { id: 'bk-06', name: 'The colophon', kind: 'footer',
    what: 'The footer’s one quiet line: the chapter’s control number, the chapter you are on, and the day it was printed.',
    probe: [{ home: 'class="colo-ctl"' }, { home: 'printed <span data-clock="date">' }] },
  { id: 'bk-07', name: 'Write to a person, from the footer', kind: 'footer',
    what: 'The footer prints the inbox beside a button that copies it and opens the mail app, and says a person answers within a working day.',
    probe: [{ home: 'class="fsh-mail"' }, { home: 'data-copied="Address copied — opening your mail app"' }] },
  { id: 'bk-08', name: 'The planner, live and deterministic', kind: 'interaction',
    what: 'Pick a track, answer the five questions with real controls, and the plan regenerates in the page — which binders, why, how many tabs and dividers — the same answers always giving the same plan; Reset restores the answers, and a Copy button carries the plan as text.',
    probe: [{ home: 'id="planner"' }, { home: 'id="bk-plan-data"' }, { js: 'function computePlan(D, a)' }, { js: 'data-plan-reset' }, { home: 'data-plan-copy' }, { home: 'name="track" value="AFH-DD"' }] },
  { id: 'bk-09', name: 'The sheet fills from the plan', kind: 'screen',
    what: 'Every contents page on the site — the one on the desk in the hero and the annotated one in The page — redraws its rows, version and control number from the plan as you answer.',
    probe: [{ home: 'data-sheet-rows' }, { js: 'data-sheet-control' }, { home: 'data-sheet-printed' }] },
  { id: 'bk-10', name: 'Seven chapters', kind: 'page',
    what: 'The screens, The plan, The library, Pricing, About and Contact are chapters of the same binder, each with its own control prefix, index tabs and contents page.',
    probe: [{ route: 'plan' }, { route: 'library' }, { route: 'pricing' }, { route: 'about' }, { route: 'contact' }, { route: 'screens' }, { html: 'data-ctl="BK-LB-01"' }] },
  { id: 'bk-11', name: 'Evidence legend', kind: 'interaction',
    what: 'Three toggles — verified, derived, open — filter which rows of the sheet show, with a running count; a struck-through toggle is a hidden tag.',
    probe: [{ home: 'data-ev-toggle="derived"' }, { js: 'evToggle' }, { home: 'data-legend-count' }] },
  { id: 'bk-12', name: 'Citation popover', kind: 'interaction',
    what: 'Hover or tap any OAR citation to see, in a paper popover, which rule it is and what it is about in plain words; without JavaScript the same link jumps to the rules list on the page.',
    probe: [{ home: 'class="cite" href="/library#cites"' }, { html: 'class="cite" href="#cites"' }, { html: 'id="cites"' }, { home: 'id="bk-cites"' }, { js: "className = 'pop'" }, { html: 'class="cite-g"' }, { js: "getElementById('cites') ? '#cites' : '/library#cites'" }] },
  { id: 'bk-13', name: 'Version diff', kind: 'interaction',
    what: 'A v1 / v2 switch on the versions table: v1 hides the current row and strikes the added tab; v2 shows the added and moved rows with the periwinkle re-plan banner and the superseded version kept.',
    probe: [{ home: 'data-vtable' }, { css: '[data-v="1"] tr[data-change="Current"]' }, { js: 'data-vtable' }, { home: 'data-v-banner' }] },
  { id: 'bk-14', name: 'Page turn', kind: 'interaction',
    what: 'Turn the page flips the sheet in three dimensions to show the tab dividers on its back; it turns back on a second press and before printing.',
    probe: [{ home: 'data-turn' }, { css: 'rotateY(180deg)' }, { js: "classList.toggle('is-turned'" }, { home: 'class="divset"' }] },
  { id: 'bk-15', name: 'Hold it at true size', kind: 'screen',
    what: 'A button renders the sheet at exactly 8.5 by 11 inches in a modal with an inch ruler along the top and side; Escape closes it.',
    probe: [{ home: 'id="lens"' }, { css: '8.5in' }, { js: 'data-lens-sheet' }, { home: 'class="ruler ruler-x"' }] },
  { id: 'bk-16', name: 'Print the contents page', kind: 'print',
    what: 'Print, p, the palette or the foot bar prints only the sheet on a letter page, with the control number in its footer and the mark as the printer’s mark at the bottom.',
    probe: [{ home: 'data-print-sheet' }, { css: '@page{size:letter' }, { css: '.cp-mark{display:flex' }, { home: 'class="cp-mark"' }] },
  { id: 'bk-17', name: 'The tab strip', kind: 'mobile',
    what: 'Between 641 and 900px the index tabs keep their column, and below that the strip under the rule follows the section in view with the early-access button at its end.',
    probe: [{ css: 'scroll-snap-type:x mandatory' }, { home: 'class="tabs-cta"' }, { js: 'list.scrollTo(' }] },
  { id: 'bk-18', name: 'The foot bar on phones', kind: 'mobile',
    what: 'A slim fixed bar above the safe area carries Print, the page number “p. n / N” driven by scroll, and Join — the two primary actions under a thumb.',
    probe: [{ home: 'class="footbar"' }, { home: 'data-page-n' }, { js: 'data-page-n' }, { css: 'var(--sab)' }] },
  { id: 'bk-19', name: 'The magnifier on phones', kind: 'mobile',
    what: 'A contents page cannot be read at 390 pixels, so on a phone a Magnify stamp — or a tap on the sheet — opens it at true size in a pannable view.',
    probe: [{ home: 'class="sheet-tap"' }, { js: "'.cp.is-hero, .cp.is-page'" }, { home: 'class="lens-scroll" data-scrollx' }] },
  { id: 'bk-20', name: 'The lamp', kind: 'dark',
    what: 'Dark mode is a desk lamp: the paper goes warm under a pool of light and the ink stays black; the choice is remembered, and the lamp icon draws its light when it is on.',
    probe: [{ home: 'data-mode-toggle' }, { css: 'html[data-mode="dark"]{--bg:#F3EBDA' }, { home: 'class="lamp-on"' }, { css: 'mix-blend-mode:multiply' }] },
  { id: 'bk-21', name: 'Ink that draws itself', kind: 'motion',
    what: 'The three forbidden words on the library chapter are struck through with a periwinkle rule that draws as they scroll in, and the four rules of holding nothing get a tick that fills as each one arrives.',
    probe: [{ html: 'class="strike"' }, { home: 'data-ledger' }, { css: 'stroke-dashoffset:0' }, { js: 'data-ledger' }] },
  { id: 'bk-22', name: 'Subscription or buy once, with the price', kind: 'interaction',
    what: 'A switch on the pricing rows moves Pro between $29 a facility a month and $149 once, and changes the wording with it.',
    probe: [{ home: 'data-sell="once"' }, { js: 'data-sell-note' }, { home: 'data-sell-p="once"' }, { js: 'x.dataset.sellP' }] },
  { id: 'bk-23', name: 'Questions with their own addresses', kind: 'interaction',
    what: 'Each question is a numbered disclosure with an address of its own; a link under the answer copies it, and arriving at that address opens the question.',
    probe: [{ home: 'class="faq-link"' }, { re: 'href="#q-1"' }, { js: 'details[id]' }, { home: 'data-copied="Link to this question copied"' }] },
  { id: 'bk-24', name: 'Write to a person', kind: 'email',
    what: 'The contact chapter carries the shared contact form with Binderkit’s own topics — Question, Early access, Which track?, Pricing, Press, Something else — and plan@binderkit.com beside it.',
    probe: [{ route: 'contact' }, { html: 'id="contactform"' }, { html: '<option value="Which track?">' }, { html: 'data-ctl="BK-CT-02"' }] },
  { id: 'bk-25', name: 'Social, in the bottom bar', kind: 'social',
    what: 'Eight platforms as a quiet row of glyphs in the footer’s bottom bar, beside the byline and the legal line.',
    probe: [{ home: 'class="soc fsh-soc"' }] },
  { id: 'bk-26', name: 'The screens chapter', kind: 'screen',
    what: 'A chapter of its own, /screens, holds all five real product screens as a full-bleed strip at the size they ship, snapped, draggable and walkable with the arrow keys.',
    probe: [{ route: 'screens' }, { html: 'data-strip="binderkit"' }, { html: 'id="plates-rail"' }, { html: 'id="plates-editor"' }] },
  { id: 'bk-27', name: 'What each screen shows', kind: 'screen',
    what: 'Every screen carries an ordinal, the tab it is filed under, a caption in the product’s own words and a “What this proves” line.',
    probe: [{ html: 'class="fs-pl">What this proves' }, { html: 'The identity line is blank and filled in by hand.' }, { html: 'A print that fails consumes no control number. Any past control number reproduces the identical artefact.' }] },
  { id: 'bk-28', name: 'Jump to a screen', kind: 'navigation',
    what: 'The strip carries an index of real anchors above it — 01 Plan · 02 Binders · 03 Editing · 04 Versions · 05 Print — which marks the screen in view and lands a single one sideways without moving the page.',
    probe: [{ html: 'class="fs-jump"' }, { html: 'aria-label="Jump to a plate"' }, { html: 'href="#plates-versions"' }] },
  { id: 'bk-29', name: 'Every screen has an address', kind: 'interaction',
    what: 'A button inside each caption copies the deep link to that one screen, so a single screen can be sent to somebody without the rest of the page around it.',
    probe: [{ html: 'data-copy="https://binderkit.com/screens#plates-print"' }, { html: 'data-copied="Link to this plate copied"' }, { css: '.plate-a{' }] },
  { id: 'bk-30', name: 'The index tabs switch the screen', kind: 'screen',
    what: 'On the front page the two halves of the product — the plan going in, the binder coming out — are one device whose screen changes when you press its index tab, with no layout shift at all.',
    probe: [{ home: 'id="sw-screens"' }, { home: 'role="tablist"' }, { home: 'data-sw-to="1"' }, { home: 'class="swx-stage"' }] },
  { id: 'bk-31', name: 'The five screens, listed', kind: 'page',
    what: 'The front page lists the five screens as numbered rows, each naming the screen, what it shows, and the address of its screen with a button that copies it.',
    probe: [{ home: 'class="preg"' }, { home: 'class="preg-i" data-plate="print"' }, { home: 'data-copied="Link to this screen copied"' }, { css: '.preg-i{' }] },
  { id: 'bk-32', name: 'Numbered pins on the guarded editor', kind: 'screen',
    what: 'Four numbered pins sit just above the element each one names, with a pointer down to it; pointing at a pin, or at its sentence, inks the pin, the row and the element inside the screen. Below 900px the sentences are the whole of it.',
    probe: [{ home: 'id="cal-editor"' }, { home: 'data-callouts' }, { home: 'class="cal-pin" data-cal="1"' }, { home: 'aria-label="Callout 1"' }, { home: 'class="cal-list"' }, { css: '.cal-pin::after{' }, { js: "closest('button.cal-pin')" }] },
  { id: 'bk-33', name: 'The contents sheet says where you are', kind: 'mobile',
    what: 'The sheet is the phone menu and it opens from any scroll position, so the section you are in is marked in it — a caret, a bold title and the control number inked.',
    probe: [{ home: 'class="toc toc-in-ch" data-spy' }, { css: '.toc-in-ch a[aria-current="true"]' }, { html: 'class="toc toc-in-ch" data-spy' }] },
  { id: 'bk-34', name: 'The next chapter, floating', kind: 'navigation',
    what: 'Once the reader is well into a chapter a small pill at the bottom-left names the next chapter — a real link that replaces the two-card pager every chapter used to end with.',
    probe: [{ home: 'class="nxt ' }, { home: 'data-next' }, { home: 'class="nxt-k">Next' }, { html: 'href="/plan" data-next' }] },
  { id: 'bk-35', name: 'The control number is the address', kind: 'interaction',
    what: 'A control number is an address in a binder, so here it is one on the web too: the stamp in every section’s margin is a button that copies the deep link to that section.',
    probe: [{ home: 'class="ctl" type="button"' }, { home: 'data-copy="https://binderkit.com/#page"' }, { home: 'data-copied="Link to this section copied"' }, { css: '.ctl-c{' }] },
  { id: 'bk-36', name: 'The palette reaches every section of every chapter', kind: 'navigation',
    what: '⌘K finds any section of any chapter by its name or by its control number and goes straight there from whichever page you are on.',
    probe: [{ home: 'data-verb="open:/plan#guardrails"' }, { home: 'data-verb="open:/library#words"' }, { js: "verb.startsWith('open:')" }] },
  { id: 'bk-37', name: 'Ask a person', kind: 'email',
    what: 'The questions end in a conversation: a three-step reach-us block with the address, a button that opens a mail draft, and the contact form one link away.',
    probe: [{ home: 'class="reach"' }, { home: 'class="reach-s"' }, { home: 'A%20question%20about%20Binderkit' }, { home: 'Use the form' }] },
  { id: 'bk-38', name: 'Real prices', kind: 'page',
    what: 'Pro is $29 a facility a month or $149 once, Scale is $69 a month, and the most-chosen tier carries a flag — on the front page and on the pricing chapter.',
    probe: [{ home: '$29<small> / facility / mo</small>' }, { home: '$69<small> / mo</small>' }, { home: '$149<small> once</small>' }, { html: 'class="tier-flag">Most facilities' }] },
  { id: 'bk-39', name: 'The three words this product owns', kind: 'interaction',
    what: 'Verified, derived and open, drawn as the evidence tags they are on the printed page, each with the sentence that defines it — the same three words on the front page, the library chapter and the legend that filters the sheet, and no fourth anywhere.',
    probe: [{ home: 'class="tag-g words"' }, { home: 'data-word="open"' }, { home: 'class="ev is-open"' }, { html: 'class="tag-g words"' }, { home: 'Three words, on every item' }] },
  { id: 'bk-40', name: 'The rules, in plain words', kind: 'page',
    what: 'Every Oregon rule the site cites, on the library chapter, grouped by licence track, with the rule number as a chip, its name, and one line saying what it is about in words a new provider can read.',
    probe: [{ html: 'class="cite-gt"' }, { html: 'Documentation and records' }, { html: 'What goes in each resident’s binder.' }, { route: 'library' }] },
  { id: 'bk-42', name: 'Icon buttons say what they do', kind: 'header',
    what: 'The lamp, share, print and contents controls each carry a plain aria-label, which the shared script shows as a tooltip on hover.',
    probe: [{ home: 'aria-label="Print the contents page"' }, { home: 'aria-label="Share this page"' }, { home: 'aria-label="Open the contents — every chapter and section"' }] },
  { id: 'bk-44', name: 'Three reasons', kind: 'page',
    what: 'Three numbered proofs at the top of the page: it holds nothing about anyone, the same answers give the same plan, and every item prints its rule.',
    probe: [{ home: 'id="why"' }, { home: 'class="art-g proof-g"' }, { home: 'data-proof="3"' }, { css: '.art-g.proof-g{' }] },
  { id: 'bk-45', name: 'Determinism, checked in the page', kind: 'interaction',
    what: 'A button runs the planner’s rule twice over the answers you have given and compares the two results character for character.',
    probe: [{ home: 'data-determinism' }, { home: 'data-det-out' }, { js: 'planTwice' }, { js: 'character for character' }] },
  { id: 'bk-46', name: 'The three guardrails, played', kind: 'interaction',
    what: 'Three buttons attempt the three edits the product refuses and each prints the refusal verbatim, with the guardrail that answered and the alternative it offers.',
    probe: [{ home: 'data-guard-try="coverage"' }, { home: 'data-gname="Cohesion"' }, { home: 'class="tryg-o"' }, { js: 'data-guard-try' }] },
  { id: 'bk-47', name: 'One row of calls', kind: 'page',
    what: 'The hero’s three calls are one row: a primary button, a secondary button and a text link to all five screens, wrapping cleanly on a phone.',
    probe: [{ home: 'class="lnk" href="/screens"' }, { css: '.lnk{' }, { home: '<span>Contents page</span>' }] },
  { id: 'bk-50', name: 'Where you are, in the foot bar', kind: 'mobile',
    what: 'The phone foot bar’s page counter carries the name of the section you are in as well as its number; a chapter’s title page is named in its h1’s own words, and a name wider than the bar is cut at a word, never mid-word or under the Join button.',
    probe: [{ home: 'data-page-name' }, { js: 'data-page-name' }, { css: '.fb-w{' }, { js: 'fitName' }, { css: '.footbar{position:fixed;left:0;right:0;bottom:0;z-index:38;display:grid;grid-template-columns:auto minmax(0,1fr) auto' }] },
  { id: 'bk-51', name: 'Three seats, three cards', kind: 'page',
    what: 'Provider, manager and viewer as three cards, each with its own punched icon — a key, a printer, reading glasses — who they are, what they do, and one line under the cards saying who may do what.',
    probe: [{ home: 'class="roles-g"' }, { home: 'data-role="viewer"' }, { home: 'class="role-key"' }, { css: '.role{' }] },
  { id: 'bk-52', name: 'The editor, on a phone', kind: 'mobile',
    what: 'Below 640px the guarded editor is the product’s own one-column build at full size rather than a desktop shell scaled to six-pixel type: the six tabs restack as rows with the guard chip on its own line, and the three guardrail tiles run full width.',
    probe: [{ css: '.tbl-a tr{display:grid;grid-template-columns:48px' }, { css: '.cal-stage .browser{--mock-z:1;zoom:1' }] },
];
