// binderkit.com — the twenty-five, each one checked against the built bytes.
export const FEATURES = [
  { id: 'bk-01', name: 'Index-tab navigation', kind: 'navigation',
    what: 'The sections are a column of binder index tabs fixed to the right edge; the tab for the section in view is pulled out and inked, and hovering a tab slides its label out.',
    probe: [{ home: 'class="tabs" aria-label="Sections" data-spy' }, { css: '.dtab[aria-current="true"]' }, { home: 'class="dtab-l">Plan</span><span class="dtab-n">1</span>' }] },
  { id: 'bk-02', name: 'Running control number', kind: 'header',
    what: 'The top rule carries BK-LP-nn, the control number of the section you are reading, and it changes as you scroll.',
    probe: [{ home: 'id="run-ctl"' }, { js: "$('#run-ctl')" }, { home: 'data-ctl="BK-LP-02"' }] },
  { id: 'bk-03', name: 'The contents sheet', kind: 'header',
    what: 'A Contents button in the rule opens a table of contents — every chapter and this page’s sections with dotted leaders — which is also the phone menu; it locks scroll and closes on Escape or any link.',
    probe: [{ home: 'aria-controls="contents" data-lock' }, { home: 'class="toc-sheet" id="contents"' }] },
  { id: 'bk-04', name: 'Keys and the ⌘K palette', kind: 'navigation',
    what: '← and → move between tabs, p prints, l switches the lamp, ? shows the card, and ⌘K opens a palette of the product’s own verbs — Re-plan, Print the contents page, Add a note, Compare versions — plus every section and chapter.',
    probe: [{ home: 'id="palette"' }, { home: 'id="keys"' }, { js: "e.key === 'ArrowRight'" }, { js: "e.key.toLowerCase() === 'k'" }, { home: 'data-verb="compare"' }] },
  { id: 'bk-05', name: 'A contents page for a footer', kind: 'footer',
    what: 'The footer is a real contents page: every section and every chapter as a numbered line with dotted leaders running to its control number.',
    probe: [{ home: 'class="foot-h">Contents' }, { css: '.toc-l{' }, { home: 'class="toc toc-ch"' }, { home: 'class="toc-n">BK-LP-11' }] },
  { id: 'bk-06', name: 'The colophon', kind: 'footer',
    what: 'The mark sits centred above the typefaces, the control number of this build and a live “printed <date>” that the page fills in from your clock.',
    probe: [{ home: 'class="colophon"' }, { home: 'data-clock="date"' }, { home: 'class="colo-ctl"' }] },
  { id: 'bk-07', name: 'Footer stamps', kind: 'footer',
    what: 'hello@binderkit.com as a punched stamp that mails, a stamp that copies the address, a stamp that shares the page and a stamp that prints — all beside the eight social stamps.',
    probe: [{ home: 'class="stamps-row"' }, { home: 'data-copied="Address copied"' }, { home: 'mailto:hello@binderkit.com' }, { home: 'class="stamp" type="button" data-share' }] },
  { id: 'bk-08', name: 'The planner, live and deterministic', kind: 'interaction',
    what: 'Pick a track, answer the five questions with real controls, and the plan regenerates in the page — which binders, why, how many tabs and dividers — the same answers always giving the same plan; Reset restores the demonstration, and a Copy button carries the plan as text.',
    probe: [{ home: 'id="planner"' }, { home: 'id="bk-plan-data"' }, { js: 'function computePlan(D, a)' }, { js: 'data-plan-reset' }, { home: 'data-plan-copy' }, { home: 'name="track" value="AFH-DD"' }] },
  { id: 'bk-09', name: 'The sheet fills from the plan', kind: 'screen',
    what: 'Every contents page on the site — the one on the desk in the hero and the annotated one in The page — redraws its rows, version and control number from the plan as you answer.',
    probe: [{ home: 'data-sheet-rows' }, { js: 'data-sheet-control' }, { home: 'data-sheet-printed' }] },
  { id: 'bk-10', name: 'Five chapters', kind: 'page',
    what: 'The plan, The library, Pricing, About and Contact are chapters of the same binder, each with its own control prefix, index tabs and contents page.',
    probe: [{ route: 'plan' }, { route: 'library' }, { route: 'pricing' }, { route: 'about' }, { route: 'contact' }, { html: 'data-ctl="BK-LB-01"' }] },
  { id: 'bk-11', name: 'Evidence legend', kind: 'interaction',
    what: 'Three toggles — verified, derived, open — filter which rows of the sheet show, with a running count; a struck-through toggle is a hidden tag.',
    probe: [{ home: 'data-ev-toggle="derived"' }, { js: 'evToggle' }, { home: 'data-legend-count' }] },
  { id: 'bk-12', name: 'Citation popover', kind: 'interaction',
    what: 'Hover or tap any OAR citation to see, in a paper popover, which chapter and section it is and its evidence line; without JavaScript the same link jumps to the glossary of citations on the page.',
    probe: [{ home: 'class="cite" href="#cites"' }, { home: 'id="cites"' }, { js: "className = 'pop'" }] },
  { id: 'bk-13', name: 'Version diff', kind: 'interaction',
    what: 'A v1 / v2 switch on the versions table: v1 hides the current row and strikes the added tab; v2 shows the added and moved rows with the periwinkle re-plan banner and the superseded version kept.',
    probe: [{ home: 'data-vtable' }, { css: '[data-v="1"] tr[data-change="Current"]' }, { js: 'data-vtable' }, { home: 'data-v-banner' }] },
  { id: 'bk-14', name: 'Page turn', kind: 'interaction',
    what: 'Turn the page flips the sheet in three dimensions to show the tab dividers on its back; it turns back on a second press and before printing.',
    probe: [{ home: 'data-turn' }, { css: 'rotateY(180deg)' }, { js: "classList.toggle('is-turned'" }, { home: 'class="divset"' }] },
  { id: 'bk-15', name: 'Hold it at true size', kind: 'screen',
    what: 'A button renders the sheet at exactly 8.5 by 11 inches — 816 by 1056 pixels — in a modal with an inch ruler along the top and side; Escape closes it.',
    probe: [{ home: 'id="lens"' }, { css: '8.5in' }, { js: 'data-lens-sheet' }, { home: 'class="ruler ruler-x"' }] },
  { id: 'bk-16', name: 'Print the contents page', kind: 'print',
    what: 'Print, p, the palette or the foot bar prints only the sheet on a letter page, with the control number in its footer and the mark as the printer’s mark at the bottom.',
    probe: [{ home: 'data-print-sheet' }, { css: '@page{size:letter' }, { css: '.cp-mark{display:flex' }, { home: 'class="cp-mark"' }] },
  { id: 'bk-17', name: 'The tab strip on phones', kind: 'mobile',
    what: 'Under the top rule the index tabs become a scroll-snapping strip — 1 Plan · 2 Page · 3 Library … — that follows the section in view, with the early-access button at its end.',
    probe: [{ css: 'scroll-snap-type:x mandatory' }, { home: 'class="tabs-cta"' }, { js: "list.scrollTo(" }] },
  { id: 'bk-18', name: 'The foot bar on phones', kind: 'mobile',
    what: 'A slim fixed bar above the safe area carries Print, the page number “p. n / N” driven by scroll, and Join — the two primary actions under a thumb.',
    probe: [{ home: 'class="footbar"' }, { home: 'data-page-n' }, { js: 'data-page-n' }, { css: 'env(safe-area-inset-bottom)' }] },
  { id: 'bk-19', name: 'The magnifier on phones', kind: 'mobile',
    what: 'A contents page cannot be read at 390 pixels, so on a phone a Magnify stamp — or a tap on the sheet — opens it at true size in a pannable view.',
    probe: [{ home: 'class="sheet-tap"' }, { js: "'.cp.is-hero, .cp.is-page'" }, { home: 'class="lens-scroll" data-scrollx' }] },
  { id: 'bk-20', name: 'The lamp', kind: 'dark',
    what: 'Dark mode is a desk lamp: the paper goes warm under a pool of light and the ink stays black; the choice is remembered, and the lamp icon draws its light when it is on.',
    probe: [{ home: 'data-mode-toggle' }, { css: 'html[data-mode="dark"]{--bg:#F3EBDA' }, { home: 'class="lamp-on"' }, { css: 'mix-blend-mode:multiply' }] },
  { id: 'bk-21', name: 'Ink that draws itself', kind: 'motion',
    what: 'The three forbidden words are struck through with a periwinkle rule that draws as they scroll in, and the six rules of holding nothing get a tick that fills as each one arrives.',
    probe: [{ home: 'class="strike"' }, { home: 'data-ledger' }, { css: 'stroke-dashoffset:0' }, { js: 'data-ledger' }] },
  { id: 'bk-22', name: 'Subscription or single purchase', kind: 'interaction',
    what: 'A switch on the pricing rows changes the wording between subscription and single purchase — open item #9 — and never the number, which stays Early access.',
    probe: [{ home: 'data-sell="once"' }, { js: 'data-sell-note' }, { html: 'data-once="' }] },
  { id: 'bk-23', name: 'Questions with their own addresses', kind: 'interaction',
    what: 'Each question is a numbered disclosure with an address of its own; a link under the answer copies it, and arriving at that address opens the question.',
    probe: [{ home: 'class="faq-link"' }, { re: 'href="#q-1"' }, { js: 'details[id]' }, { home: 'data-copied="Link to this question copied"' }] },
  { id: 'bk-24', name: 'Write to a person', kind: 'email',
    what: 'The contact chapter carries the shared contact form with Binderkit’s own topics — Question, Early access, Which track?, Pricing, Press, Something else — and hello@ beside it.',
    probe: [{ route: 'contact' }, { html: 'id="contactform"' }, { html: '<option value="Which track?">' }, { html: 'data-ctl="BK-CT-02"' }] },
  { id: 'bk-25', name: 'Social stamps', kind: 'social',
    what: 'All eight platforms as square punched stamps that ink on hover; on the contact chapter they carry their handles.',
    probe: [{ home: 'class="soc stamps"' }, { css: '.stamps .soc-i{' }, { re: 'class="soc-i" data-net="bluesky"' }, { html: 'class="soc stamps is-text"' }] },
];
