// careshop.app — the features, each verified against the built bytes.
// A probe is a substring that leaves with the feature. Rewritten 2026-09-23
// with the review: the price-tag brand, the phone loop strip, the walk-on
// pager, the stock take, the ladder, the demo-data chips and the confession
// slips are gone, and what replaced them is pinned here instead.
export const FEATURES = [
  { id: 'cs-01', name: 'The aisle strip', kind: 'navigation',
    what: 'The navigation is a scroll-snapping row of hanging aisle signs; the aisle you are in is lit, and ←/→ walk you to the next one.',
    probe: [{ home: 'class="strip" id="aisles"' }, { home: 'class="sign" href="#loop"' }, { css: '.sign[aria-current]' }, { js: 'ArrowRight' }] },
  { id: 'cs-02', name: 'The wordmark, and the condensing header', kind: 'header',
    what: 'The basket mark on its tile beside the name, and nothing else: no tag, no hole, no tail. Once you scroll the header condenses and the aisle signs drop to one line.',
    probe: [{ home: 'class="brand" href="/"' }, { home: 'class="brand-n"' }, { css: '.brand-n{' }, { css: '.aisle[data-stuck] .sign-a{display:none}' }] },
  { id: 'cs-03', name: 'The receipt drawer', kind: 'mobile',
    what: 'On a phone the tally button opens the menu as a till slip from the bottom: sections as receipt lines with dotted leaders, TOTAL is the Start free button.',
    probe: [{ home: 'aria-controls="drawer"' }, { home: 'class="drawer" id="drawer" hidden' }, { css: '.drawer-sheet{' }, { css: '@keyframes rise' }] },
  { id: 'cs-04', name: 'The bottom tally bar', kind: 'mobile',
    what: 'A thin fixed bar on phones: the store chip, "You are in: <aisle>" that follows your scroll, and Start free under the thumb.',
    probe: [{ home: 'class="tally-bar" id="tally-bar"' }, { home: 'data-where' }, { js: '[data-where]' }, { css: 'var(--sab)' }] },
  { id: 'cs-05', name: 'Lights: the pantry light-pull', kind: 'dark',
    what: 'The mode switch is a light-pull cord that says what it does, in its name and in a tooltip on hover; pull it and the lights go off in the pantry, a deep clay-black ground with warm paper type, remembered.',
    probe: [{ home: 'class="cord" type="button" data-mode-toggle' }, { home: 'aria-label="Lights: switch between light and dark"' }, { css: ':root[data-mode="dark"]' }, { css: '.cord:hover .cord-pull' }] },
  { id: 'cs-06', name: 'The loop ring turns with the stations', kind: 'navigation',
    what: 'Seven stations on a ring that is sticky beside the station list and turns with the section’s own scroll; the lit node and the lit list row are the same station, and each node is a link to its row.',
    probe: [{ home: 'class="ring-rot"' }, { home: 'class="ring-n" href="#station-1"' }, { home: 'data-ring-wrap data-scroll-p="parent"' }, { js: "setProperty('--lp'" }, { js: "classList.toggle('is-on', k === i)" }, { css: '.ring-n.is-lit circle' }, { css: '.loop-v{grid-column:2;grid-row:1 / span 3;position:sticky' }] },
  { id: 'cs-07', name: 'The station rows light up, and point at their aisle', kind: 'interaction',
    what: 'Each station is one line with a number; the one the ring is on lifts onto a card, and an arrow on the row jumps to the aisle it lives in.',
    probe: [{ home: 'data-stations' }, { home: 'id="station-7"' }, { home: 'class="st-go" href="#cook"' }, { css: '.stations li.is-on{' }] },
  { id: 'cs-08', name: 'The par slider', kind: 'interaction',
    what: 'Drag the par on Rice above what is on hand and the row turns Short and a request appears in the queue; below, it goes Stocked and the request leaves.',
    probe: [{ home: 'data-par-range' }, { home: 'type="range"' }, { js: 'Par breach' }] },
  { id: 'cs-09', name: 'Approve the queue', kind: 'interaction',
    what: 'Buttons move a line Pending → Approved → In cart → Bought with a slide, and a rubber stamp counts what you approved.',
    probe: [{ home: 'data-approve-btn' }, { home: 'data-approve-stamp' }, { js: "'In cart', 'Bought'" }, { css: '@keyframes stamp' }] },
  { id: 'cs-10', name: 'The allergen toggle', kind: 'interaction',
    what: 'Room 3’s tags as chips; toggle peanut off and the Thursday warning on the Menu phone clears, toggle it on and the warning is back. It warns, never prevents.',
    probe: [{ home: 'data-tag="peanut"' }, { home: 'data-menu-phone' }, { js: 'data-allergen-note' }] },
  { id: 'cs-11', name: 'The reserve calculator', kind: 'interaction',
    what: 'Days × licensed beds × per bed per day gives the target, the gap against on-hand updates as you type, and a toggle switches gallons and litres.',
    probe: [{ home: 'data-reserve data-unit="gal"' }, { home: 'data-unit-set="l"' }, { js: '3.785' }] },
  { id: 'cs-12', name: 'Price memory', kind: 'interaction',
    what: 'Tap a shelf item and the ledger’s last price at the shop it was bought in opens under it.',
    probe: [{ home: 'data-price-memory' }, { home: 'Last paid $4.98 at WinCo' }, { js: '[data-pm]' }] },
  { id: 'cs-13', name: 'The barcode scan', kind: 'screen',
    what: 'On the hero phone a scan line sweeps a barcode and the item lands at the top of the Stock list; Scan again runs it once more.',
    probe: [{ home: 'class="scan" data-scan' }, { home: 'data-scan-again' }, { css: '@keyframes sweep' }, { js: 'Scanned just now' }] },
  { id: 'cs-14', name: 'The receipt that prints itself', kind: 'footer',
    what: 'The footer is a short till receipt that prints line by line as it enters the viewport, then tears at a perforated edge.',
    probe: [{ home: 'class="rc rc-foot" data-receipt' }, { js: "classList.add('is-printed')" }, { css: '.rc::after' }] },
  { id: 'cs-15', name: 'The fan opens with the scroll', kind: 'motion',
    what: 'Three phones fan out inside their own column and open a little further as the reader scrolls past, driven by the shared scroll progress. Three dots under them, or a tap on a side phone, bring that phone to the front; on a phone the fan is a swipeable snap carousel and the same dots scroll it.',
    probe: [{ home: 'class="fan" data-fan data-scroll-p' }, { home: 'data-fan-dots' }, { css: 'rotate(calc(-6deg - var(--sp) * 4deg))' }, { css: 'scroll-snap-type:x mandatory' }, { css: '.fan-dots{display:flex' }, { css: '.fan-p:not(.is-c){cursor:pointer}' }, { js: 'fan-dot' }, { js: "phones[c].classList.remove('is-c')" }] },
  { id: 'cs-16', name: 'Expiry Watch, sortable', kind: 'interaction',
    what: 'The dated items as a ladder of days bars; two buttons sort by urgency or by money at risk, and the rows slide into their new order.',
    probe: [{ home: 'data-sort="urgency"' }, { home: 'data-sort="value"' }, { js: 'getBoundingClientRect().top]' }] },
  { id: 'cs-17', name: 'The store picker', kind: 'interaction',
    what: 'WinCo, Costco, Fred Meyer as chips; the shopping list re-totals from what the ledger knows at that shop and says when the total is incomplete.',
    probe: [{ home: 'data-store="Costco"' }, { home: 'data-sp-total' }, { js: 'Incomplete' }] },
  { id: 'cs-18', name: 'Cook mode, completed once', kind: 'screen',
    what: 'Tap Complete on step four and the two numbers on the shelf line go down with a toast; tap it again and it tells you stock went down once.',
    probe: [{ home: 'data-cook-complete' }, { home: 'class="shelf-line"' }, { home: 'data-shelf="rice"' }, { js: 'written once' }] },
  { id: 'cs-19', name: '⌘K, the product’s verbs', kind: 'navigation',
    what: 'Command-K opens a palette of CareShop’s own verbs, the other rooms and every screen; type to filter, arrows to move.',
    probe: [{ home: 'class="pal" id="palette"' }, { home: 'data-verb="scan an item"' }, { home: 'class="pal-h"' }, { home: '/shelf#shelf-cook' }, { js: "key.toLowerCase() === 'k'" }] },
  { id: 'cs-20', name: 'Print the list', kind: 'print',
    what: 'A Print the list button prints the shop screen’s aisles as a clean checklist and nothing else.',
    probe: [{ home: 'class="btn" data-print' }, { home: 'class="print-list"' }, { css: '@media print' }, { css: '.print-list{display:block !important' }] },
  { id: 'cs-21', name: 'Write to a person, from the receipt', kind: 'footer',
    what: 'The receipt prints kitchen@careshop.app with a Copy button that also opens the mail app, a Share button and a Write link.',
    probe: [{ home: 'data-copy="kitchen@careshop.app"' }, { home: 'data-copied="Address copied — opening your mail app"' }, { home: 'data-share data-share-title' }, { home: 'mailto:kitchen@careshop.app' }] },
  { id: 'cs-22', name: 'The dated receipt, the plans line and the tear', kind: 'footer',
    what: 'The receipt header carries today’s date and no clock, the PLANS line reads the real price ladder, TO BEGIN reads NO CARD, and the perforation is a link back to the top.',
    probe: [{ home: 'data-clock="date"' }, { home: '<span>PLANS</span>' }, { home: 'Pro $19' }, { home: '<b>NO CARD</b>' }, { home: 'class="rc-tearlink" href="#main"' }] },
  { id: 'cs-23', name: 'The numbers count up', kind: 'motion',
    what: 'Four facts about how the product is built count up when they enter view: $0 to start, five origins, six front doors, ten citations.',
    probe: [{ home: 'data-count="10"' }, { home: 'origins for a buy request' }, { js: 'requestAnimationFrame(step)' }] },
  { id: 'cs-24', name: 'The rules page: how sure we are', kind: 'page',
    what: 'On /rules the ten citations sit beside a legend; tap confirmed, inferred or unreviewed and a popover says what it means, one open at a time.',
    probe: [{ route: 'rules' }, { html: 'data-conf-legend' }, { html: 'OAR 411-050-0725' }, { js: '[data-conf-legend]' }] },
  { id: 'cs-25', name: 'The stickers, and the write page', kind: 'social',
    what: 'Eight label-shaped social stickers peel on hover and on press; on /write they carry their handles beside the contact form with CareShop’s own topics.',
    probe: [{ home: 'class="soc rc-soc"' }, { css: '.rc-soc .soc-i:hover' }, { route: 'write' }, { html: '<b>KITCHEN@CARESHOP.APP</b>' }, { html: 'A house wants to switch' }, { js: 'is-peel' }] },
  { id: 'cs-26', name: 'The shelf: all eight screens, full size', kind: 'demo',
    what: 'A route of its own carries a full-bleed rail of every screen the product has, each on a paper plinth with its own id, and a row of tickets that jumps to any of them.',
    probe: [{ route: 'shelf' }, { html: 'id="shelf-rail"' }, { html: 'data-strip="careshop"' }, { html: 'id="shelf-today-mgr"' }, { css: '.fs-jump a[aria-current="true"]' }] },
  { id: 'cs-27', name: 'What this proves, under every screen', kind: 'demo',
    what: 'Every screen on the shelf carries a caption and, under it, the one rule of the product that screen is evidence for.',
    probe: [{ html: 'class="fs-pv"' }, { html: 'class="fs-pl"' }, { html: 'What this proves' }, { css: '.fs-pv{' }] },
  { id: 'cs-28', name: 'The ticket switcher: a device whose screen changes', kind: 'demo',
    what: 'Today is one phone with a two-ticket rail over it, a real tablist with one panel per screen, and the stage keeps its box so switching moves nothing on the page.',
    probe: [{ home: 'data-switch' }, { home: 'id="sw-today-p1"' }, { home: 'data-sw-to="1"' }, { css: '.swx-tab[aria-selected="true"]' }] },
  { id: 'cs-29', name: 'The till, annotated', kind: 'demo',
    what: 'The buy queue drawn as the desktop application, with six numbered pins over it; pointing at a pin lights the row, the sentence and the element it quotes.',
    probe: [{ route: 'shelf' }, { html: 'data-callouts' }, { html: 'class="cal-pin"' }, { html: 'data-sel=".conf-a"' }] },
  { id: 'cs-30', name: 'The entrance board', kind: 'navigation',
    what: 'Every stop on the page as a numbered shelf ticket, in walk order, and the one you are standing in is lit and scrolled into view as you go.',
    probe: [{ home: 'data-dir' }, { home: 'class="dir-i"' }, { js: "$$('.dir-i')" }, { css: '.dir-i[aria-current]' }] },
  { id: 'cs-31', name: 'The next room, floating', kind: 'navigation',
    what: 'The two-card previous/next block at the foot of every page is gone; the walk shows as one small pill, bottom-centre, revealed once the reader is well into the page: Next · The loop.',
    probe: [{ home: 'class="nxt " href="/loop" data-next' }, { html: 'data-next aria-label="Next page: The till' }, { css: '.nxt{left:50%;right:auto;translate:-50% 0}' }] },
  { id: 'cs-32', name: 'Ask a person: the questions end in a conversation', kind: 'contact',
    what: 'After the questions on the front page, on /pricing, on /rules and on /about, a three-step block: write, a person answers within a working day, see it run. One button opens the mail app with the subject filled in, the other goes to the form.',
    probe: [{ home: 'class="reach" id="reach"' }, { home: 'A person answers' }, { home: 'href="/write">Use the form' }, { html: 'id="reach-pricing"' }, { html: 'id="reach-rules"' }, { html: 'id="reach-about"' }, { css: '.reach{background:var(--paper)' }] },
  { id: 'cs-33', name: 'Copy the address of the aisle you are in', kind: 'mobile',
    what: 'The dock’s “You are in” is a button: press it and the deep link to the aisle on screen is on the clipboard.',
    probe: [{ home: 'data-here-copy' }, { home: 'data-copied="Link to this aisle copied"' }, { js: "cp.setAttribute('data-copy'" }] },
  { id: 'cs-34', name: 'Every screen has an address', kind: 'navigation',
    what: 'On the shelf, each of the eight screens is listed with an anchor and a Copy button that hands the whole URL over.',
    probe: [{ route: 'shelf' }, { html: 'addr-c' }, { html: 'data-copied="Link to Today · a manager copied"' }] },
  { id: 'cs-35', name: 'The four labels, and no fifth', kind: 'page',
    what: 'Short, Expiring, Stocked, Over: the only four states this product marks, printed with the definition of each.',
    probe: [{ route: 'shelf' }, { html: 'class="labels-l"' }, { html: 'More than the shelf needs' }, { css: '.labels-i' }] },
  { id: 'cs-36', name: 'Three price tags, equal', kind: 'pricing',
    what: 'Free, Pro and Scale as three cards of the same shape: the price large with the unit small, three lines each, one button each, Most houses on Pro. The same cards on the front page and on /pricing.',
    probe: [{ home: 'class="tier is-main"' }, { home: '$19<small> / house / mo</small>' }, { home: 'Spend across houses' }, { html: 'data-cta="pricing-page"' }, { css: '.tier-p small{' }] },
  { id: 'cs-37', name: 'The terms of the till', kind: 'pricing',
    what: 'A receipt slip on /pricing of how the product is sold: on the web, never through a purchase sheet, per house, cancel in one tap.',
    probe: [{ route: 'pricing' }, { html: 'rc-terms' }, { html: 'TERMS OF THE TILL' }, { html: 'NO CARD TO BEGIN. CANCEL IN ONE TAP.' }] },
  { id: 'cs-38', name: 'Residents: three cards and one line', kind: 'page',
    what: 'The record chapter is three short cards, the resident record, why initials are not a defence, tray notes, and one calm line under them.',
    probe: [{ home: '<span class="strip-l">The resident record</span>' }, { home: 'Room 2 · A' }, { home: 'CareShop runs the kitchen. Nothing clinical is ever stored.' }, { css: '.ev{grid-template-columns:repeat(3,minmax(0,1fr))' }] },
  { id: 'cs-39', name: 'Six seats, six stickers', kind: 'design',
    what: 'Every role card on the front page, and every seat on /features, opens with its own sticker on a sage tile: the licence holder’s key, the manager’s clipboard, the caregiver’s scan, the buyer’s cart, the link a spouse opens, the operator’s wrench.',
    probe: [{ home: 'class="role-top"' }, { home: 'class="role-i"' }, { css: '.role-i{' }, { route: 'features' }, { html: 'class="fseat-i"><span class="role-top"><span class="role-i">' }] },
  { id: 'cs-40', name: 'Five origins, and no sixth', kind: 'interaction',
    what: 'Each of the five things that can file a buy request opens to show the queue line it produced. One open at a time, with no script.',
    probe: [{ route: 'features' }, { html: 'name="careshop-origin"' }, { html: 'class="orig-row"' }, { css: '.orig-d[open]' }] },
  { id: 'cs-41', name: 'Zone is not aisle is not category', kind: 'interaction',
    what: 'The same five things sorted the two ways a person walks them, with the third axis defined and deliberately not listed.',
    probe: [{ route: 'stock' }, { html: 'name="careshop-axis"' }, { html: 'class="axes-l"' }, { html: '19 aisles' }] },
  { id: 'cs-42', name: 'Twelve rules it applies to itself', kind: 'page',
    what: 'The product’s own rules on /rules, twelve cards, each one a sentence.',
    probe: [{ route: 'rules' }, { html: 'class="gov"' }, { html: 'The curation rule' }, { html: 'The ledger rule' }] },
  { id: 'cs-43', name: 'What leaves the house', kind: 'page',
    what: 'A message out of the system carries a house code and a count and never a resident, a diet, an allergen or an item name.',
    probe: [{ route: 'rules' }, { html: 'id="h-egress"' }, { html: 'A message carries a code and a count.' }] },
  { id: 'cs-44', name: 'The shopper with no account', kind: 'page',
    what: 'The link a spouse doing the Costco run opens: what it grants, and what it grants nothing of.',
    probe: [{ route: 'loop' }, { html: 'id="h-token"' }, { html: 'class="tok-c is-no"' }, { css: '.tok-c.is-no' }] },
  { id: 'cs-45', name: 'The closed lists, counted', kind: 'page',
    what: 'The sizes of the vocabularies an allergen check matches on: 401 catalogue items, 20 categories, 19 aisles, 9 zones, 18 diet tags, 9 allergens.',
    probe: [{ route: 'features' }, { html: 'class="vocab-n"' }, { html: 'class="vocab"' }, { css: '.vocab-n{' }] },
  { id: 'cs-46', name: 'The compact demos', kind: 'design',
    what: 'Every demo card on the front page sits at a working size: one instrument head, recessed rows, a one-line footnote, and the phone crop beside it at 280px.',
    probe: [{ css: '.demo{--demo-pad:clamp(16px,1.4vw,22px)' }, { css: '.demo-f{font-size:var(--cs-sm)' }, { css: '.crop{height:470px;max-width:280px}' }] },
  { id: 'cs-47', name: 'The keyboard map', kind: 'page',
    what: 'Every key the store answers to, printed on /shelf: ⌘K for the palette, ←/→ for the aisles and the rail, Home and End on a switcher, Esc to close.',
    probe: [{ route: 'shelf' }, { html: 'class="keys-k"' }, { html: 'Open the palette: the verbs, the nine rooms' }, { css: '.keys kbd' }] },
  { id: 'cs-48', name: 'The movement, and its seven fields', kind: 'page',
    what: 'Every change to on-hand is one immutable movement carrying the item, the house, the delta, a reason, the actor, the time and the key that records it exactly once.',
    probe: [{ route: 'stock' }, { html: 'class="mvt-k"' }, { html: 'class="mvt"' }, { css: '.mvt-k{' }] },
  { id: 'cs-49', name: 'Two people, one shelf', kind: 'page',
    what: 'What the product does when two people count the same item, and when a number arrives far outside the last one: accepted and marked, never silently refused.',
    probe: [{ route: 'stock' }, { html: 'Two people, one shelf' }, { html: 'Out of range is accepted, and marked' }] },
  { id: 'cs-50', name: 'About: what is true, and one line', kind: 'page',
    what: '/about is what the product does, six things that are true of it, the one line it will not cross, and a person to write to. Nothing about a roadmap and nothing about a sibling product.',
    probe: [{ route: 'about' }, { html: 'What is true of it.' }, { html: 'class="take-g is-one"' }, { html: 'Made in Oregon, for Oregon houses.' }] },
];
