// careshop.app — the twenty-five, each verified against the built bytes.
// A probe is a substring that leaves with the feature.
export const FEATURES = [
  { id: 'cs-01', name: 'The aisle strip', kind: 'navigation',
    what: 'The navigation is a scroll-snapping row of hanging aisle signs; the aisle you are in is lit, and ←/→ walk you to the next one.',
    probe: [{ home: 'class="strip" id="aisles"' }, { home: 'class="sign" href="#loop"' }, { css: '.sign[aria-current]' }, { js: 'ArrowRight' }] },
  { id: 'cs-02', name: 'The price-tag brand and the condensing header', kind: 'header',
    what: 'The mark hangs on a punched price tag at the left; once you scroll the header condenses and the aisle signs drop to one line.',
    probe: [{ home: 'class="tagb"' }, { home: 'class="tagb-hole"' }, { css: '.aisle[data-stuck] .sign-a{display:none}' }] },
  { id: 'cs-03', name: 'The receipt drawer', kind: 'mobile',
    what: 'On a phone the tally button opens the menu as a till slip from the bottom: sections as receipt lines with dotted leaders, TOTAL is the Start free button.',
    probe: [{ home: 'aria-controls="drawer"' }, { home: 'class="drawer" id="drawer" hidden' }, { css: '.drawer-sheet{' }, { css: '@keyframes rise' }] },
  { id: 'cs-04', name: 'The bottom tally bar', kind: 'mobile',
    what: 'A thin fixed bar on phones: the store chip, "You are in: <aisle>" that follows your scroll, and Start free under the thumb.',
    probe: [{ home: 'class="tally-bar" id="tally-bar"' }, { home: 'data-where' }, { js: '[data-where]' }, { css: 'env(safe-area-inset-bottom)' }] },
  { id: 'cs-05', name: 'Lights: the pantry light-pull', kind: 'dark',
    what: 'The mode switch is a light-pull cord; pull it and the lights go off in the pantry — a deep clay-black ground with warm paper type, remembered.',
    probe: [{ home: 'class="cord" type="button" data-mode-toggle' }, { css: ':root[data-mode="dark"]' }, { css: '.cord:hover .cord-pull' }] },
  { id: 'cs-06', name: 'The loop ring', kind: 'navigation',
    what: 'Seven stations on a ring that turns as you scroll, each a link to its aisle; the station under the pointer is lit and named.',
    probe: [{ home: 'class="ring-rot"' }, { home: 'class="ring-n" href="#stock"' }, { js: "setProperty('--lp'" }, { css: '.ring-n.is-lit circle' }] },
  { id: 'cs-07', name: 'The loop strip on phones', kind: 'mobile',
    what: 'On a phone the ring becomes a horizontal snapping strip of station cards; the one in view lights up and the dots follow.',
    probe: [{ home: 'class="loop-strip" data-loop-strip' }, { css: '.loop-strip{display:flex' }, { js: '[data-loop-strip]' }] },
  { id: 'cs-08', name: 'The par slider', kind: 'interaction',
    what: 'Drag the par on Rice above what is on hand and the row turns Short and a request appears in the queue; below, it goes Stocked and the request leaves.',
    probe: [{ home: 'data-par-range' }, { home: 'type="range"' }, { js: 'Par breach' }] },
  { id: 'cs-09', name: 'Approve the queue', kind: 'interaction',
    what: 'Buttons move a line Pending → Approved → In cart → Bought with a slide, and a rubber stamp counts what you approved.',
    probe: [{ home: 'data-approve-btn' }, { home: 'data-approve-stamp' }, { js: "'In cart', 'Bought'" }, { css: '@keyframes stamp' }] },
  { id: 'cs-10', name: 'The allergen toggle', kind: 'interaction',
    what: 'Room 3’s tags as chips; toggle peanut off and the Thursday warning on the Menu phone clears, toggle it on and the warning is back — it warns, never prevents.',
    probe: [{ home: 'data-tag="peanut"' }, { home: 'data-menu-phone' }, { js: 'data-allergen-note' }] },
  { id: 'cs-11', name: 'The reserve calculator', kind: 'interaction',
    what: 'Days × licensed beds × per bed per day gives the target, the gap against on-hand updates as you type, and a toggle switches gallons and litres client-side.',
    probe: [{ home: 'data-reserve data-unit="gal"' }, { home: 'data-unit-set="l"' }, { js: '3.785' }] },
  { id: 'cs-12', name: 'Price memory', kind: 'interaction',
    what: 'Tap a shelf item and the ledger’s last price at the shop it was bought in opens under it, in the instrument’s own figures.',
    probe: [{ home: 'data-price-memory' }, { home: 'Last paid $4.98 at WinCo' }, { js: '[data-pm]' }] },
  { id: 'cs-13', name: 'The barcode scan', kind: 'screen',
    what: 'On the hero phone a scan line sweeps a barcode and the item lands at the top of the Stock list; Scan again runs it once more.',
    probe: [{ home: 'class="scan" data-scan' }, { home: 'data-scan-again' }, { css: '@keyframes sweep' }, { js: 'Scanned just now' }] },
  { id: 'cs-14', name: 'The receipt that prints itself', kind: 'footer',
    what: 'The footer is a till receipt that prints line by line as it enters the viewport, then tears at a zig-zag edge.',
    probe: [{ home: 'class="rc rc-foot" data-receipt' }, { js: "classList.add('is-printed')" }, { css: '.rc::after' }] },
  { id: 'cs-15', name: 'The fanned phones', kind: 'mobile',
    what: 'Three phones fan out and spread on hover on a desktop; on a phone they become a swipeable snap carousel with dots that follow the scroll.',
    probe: [{ home: 'class="fan" data-fan' }, { home: 'data-fan-dots' }, { css: 'scroll-snap-type:x mandatory' }, { js: 'fan-dot' }] },
  { id: 'cs-16', name: 'Expiry Watch, sortable', kind: 'interaction',
    what: 'The dated items as a ladder of days bars; two buttons sort by urgency or by money at risk, and the rows slide into their new order.',
    probe: [{ home: 'data-sort="urgency"' }, { home: 'data-sort="value"' }, { js: 'getBoundingClientRect().top]' }] },
  { id: 'cs-17', name: 'The store picker', kind: 'interaction',
    what: 'WinCo, Costco, Fred Meyer as chips; the shopping list re-totals from what the ledger knows at that shop and says when the total is incomplete.',
    probe: [{ home: 'data-store="Costco"' }, { home: 'data-sp-total' }, { js: 'Incomplete' }] },
  { id: 'cs-18', name: 'Cook mode, completed once', kind: 'screen',
    what: 'Tap Complete on step four and the shelf numbers go down with a toast; tap it again and it tells you stock went down once.',
    probe: [{ home: 'data-cook-complete' }, { home: 'data-shelf="rice"' }, { js: 'written once' }] },
  { id: 'cs-19', name: '⌘K, the product’s verbs', kind: 'navigation',
    what: 'Command-K opens a palette of CareShop’s own verbs — Scan an item, Approve the queue, Make the shopping list, Cook this — that jump to sections and pages; type to filter, arrows to move.',
    probe: [{ home: 'class="pal" id="palette"' }, { home: 'data-verb="scan an item"' }, { js: "key.toLowerCase() === 'k'" }] },
  { id: 'cs-20', name: 'Print the list', kind: 'print',
    what: 'A Print the list button prints the shop screen’s aisles as a clean checklist and nothing else — the page has a print stylesheet that hides the store.',
    probe: [{ home: 'class="btn" data-print' }, { home: 'class="print-list"' }, { css: '@media print' }, { css: '.print-list{display:block !important' }] },
  { id: 'cs-21', name: 'Write to a person, from the receipt', kind: 'footer',
    what: 'The receipt prints hello@careshop.app with a Copy button, a Share button and a Write link, so the address is one tap away on every page.',
    probe: [{ home: 'data-copy="hello@careshop.app"' }, { home: 'data-share data-share-title' }, { home: 'mailto:hello@careshop.app' }] },
  { id: 'cs-22', name: 'The live-dated receipt and the tear line', kind: 'footer',
    what: 'The receipt header carries today’s date and the time, the subtotal line reads the real price ladder, and the perforation is a link back to the top.',
    probe: [{ home: 'data-clock="date"' }, { home: 'SUBTOTAL' }, { home: 'Pro $19' }, { home: 'class="rc-tearlink" href="#main"' }] },
  { id: 'cs-23', name: 'The numbers count up', kind: 'motion',
    what: 'The four honest figures in the numbers band count up from zero when they enter view.',
    probe: [{ home: 'data-count="14.20"' }, { js: 'requestAnimationFrame(step)' }] },
  { id: 'cs-24', name: 'The rules page: how sure we are', kind: 'page',
    what: 'On /rules the ten citations sit beside a legend; tap confirmed, inferred or unreviewed and a popover says what it means — one open at a time.',
    probe: [{ route: 'rules' }, { html: 'data-conf-legend' }, { html: 'OAR 411-050-0725' }, { js: '[data-conf-legend]' }] },
  { id: 'cs-25', name: 'The stickers, and the write page', kind: 'social',
    what: 'Eight label-shaped social stickers peel on hover and on press; on /write they carry their handles beside the contact form with CareShop’s own topics.',
    probe: [{ home: 'class="soc rc-soc"' }, { css: '.rc-soc .soc-i:hover' }, { route: 'write' }, { html: 'A house wants to switch' }, { js: 'is-peel' }] },
];
