// The things the Cohort site does, each checked against the built bytes by
// tools/check.mjs. A probe is chosen so that removing the feature would make
// it fail. Rewritten 2026-09-23 for the round-3 review: the index without
// hours, the docked keys, the reach-us block, the floating next, the priced
// tiers, and nothing that confesses.

export const FEATURES = [
  { id: 'ch-01', name: 'The rail', kind: 'navigation',
    what: 'The header navigation is a rail of stops; a coral now-dot travels it with the scroll and the current stop fills.',
    probe: [{ home: 'class="rail"' }, { home: 'class="rail-now"' }, { js: "setProperty('--now'" }] },
  { id: 'ch-02', name: 'The phone menu', kind: 'mobile',
    what: 'On a phone the menu is a full-screen sheet listing the stops, the five screens, the pages, the day/night switch and the text-size switch.',
    probe: [{ home: 'id="sheet"' }, { home: 'class="ssheet-hr"' }, { css: '.ssheet{' }] },
  { id: 'ch-03', name: 'The phone tab bar, with the mark in the centre', kind: 'mobile',
    what: 'A fixed, safe-area-aware bottom bar mirrors the app’s tab bar — Today, Shift, the mark as the door to your house, Record, Join — and marks the section in view.',
    probe: [{ home: 'class="tabs"' }, { home: 'class="tab-s tab-m"' }, { css: 'var(--sab)' }, { js: "'.tabs[data-tabs]'" }] },
  { id: 'ch-04', name: 'Day shift / Night shift', kind: 'dark',
    what: 'The dark-mode switch is a shift badge; night shift is a real palette and it reaches the phones on the page.',
    probe: [{ home: 'data-mode-toggle' }, { home: 'class="shiftb-n"' }, { css: 'html[data-mode="dark"]{' }, { js: 'phoneMode' }] },
  { id: 'ch-05', name: 'It is <time> in Oregon', kind: 'interaction',
    what: 'The hero carries a live Pacific-time clock and says which shift it is.',
    probe: [{ home: 'data-oregon' }, { home: 'data-shift-word' }, { js: "'America/Los_Angeles'" }] },
  { id: 'ch-06', name: 'The phone that follows the hours', kind: 'screen',
    what: 'A timeline of the shift with a phone beside it that changes screen at each hour and stays beside the list; on phones the screen is a pinned crop at the top of the section.',
    probe: [{ home: 'class="tour-p' }, { home: 'data-tour="incident"' }, { css: '.crop{' }, { home: 'data-tour-cap' }, { home: 'data-scroll-p="parent"' }] },
  { id: 'ch-07', name: 'Tap an hour', kind: 'interaction',
    what: 'Every hour and every step title is a control: tapping it puts that step on, switches the phone to its screen and settles the page on it.',
    probe: [{ home: 'data-tl-go' }, { home: 'class="tl-h"' }, { js: 'const settle = (li) => {' }, { js: "e.target.closest('[data-tl-go]')" }] },
  { id: 'ch-08', name: 'Keys: J, K, arrows and ?', kind: 'a11y',
    what: 'J and K step the timeline, the arrows do the same while an hour is focused, T goes to the top, and ? opens a shortcut sheet from a button docked beside the floating write-to-us.',
    probe: [{ home: 'id="keys"' }, { home: 'data-fab-side' }, { js: "e.key === 'j'" }, { js: "e.key === '?'" }] },
  { id: 'ch-09', name: 'The MAR-pass simulator', kind: 'screen',
    what: 'In the 08:00 step the phone is interactive: tap a due row, the Six Rights sheet slides up, Sign marks it Given with a stamp; loratadine raises the allergy stop and asks for a reason first.',
    probe: [{ home: 'data-tour="marpass+sheet"' }, { home: 'class="sim-reset"' }, { js: 'is-sim' }, { js: 'Override and sign' }] },
  { id: 'ch-10', name: 'Airplane mode', kind: 'interaction',
    what: 'A switch beside the 10:30 step: on, new care notes queue with a pending chip and an outbox count; off, they catch up one by one with stamps.',
    probe: [{ home: 'class="air-sw"' }, { home: 'class="air-out"' }, { js: 'data-pending' }] },
  { id: 'ch-11', name: 'The handoff composes itself', kind: 'motion',
    what: 'As the 18:45 step comes into view the sheet on the phone fills in line by line, driven by an IntersectionObserver.',
    probe: [{ home: 'data-compose-note' }, { css: '.is-compose:not(.is-done)' }, { js: "classList.add('is-compose')" }] },
  { id: 'ch-12', name: '⌘K — the product’s verbs', kind: 'navigation',
    what: 'A command palette listing the product’s own verbs — Sign a dose, File an incident, Start handover, Add an addendum — plus the screens, the stops and the pages.',
    probe: [{ home: 'id="pal"' }, { home: 'Sign a dose' }, { js: 'e.metaKey' }, { js: 'pal-none' }] },
  { id: 'ch-13', name: 'The questions, filtered', kind: 'interaction',
    what: 'A filter box above the questions narrows the disclosures as you type and counts “n of 5”.',
    probe: [{ home: 'class="faq-q"' }, { home: 'class="faq-n"' }, { js: 'faq-none' }] },
  { id: 'ch-14', name: 'Ask a person', kind: 'conversion',
    what: 'The questions end in a three-step reach-us block — write, a person answers, see it run — with the address, a mail button and the form.',
    probe: [{ home: 'class="reach"' }, { home: 'class="reach-s"' }, { home: 'data-cta="reach"' }, { css: '.reach{' }] },
  { id: 'ch-15', name: 'Pricing by houses', kind: 'interaction',
    what: 'A 1 · 2–3 · 4–9 · 10+ stepper rewrites the tier line with the price, marks the tier that covers you, and presets the waitlist’s house count.',
    probe: [{ home: 'class="hs"' }, { home: 'class="hs-line"' }, { js: "select[name=\"houses\"]" }, { js: '$39 per house' }, { route: 'pricing' }] },
  { id: 'ch-16', name: 'A price, with its unit small', kind: 'pricing',
    what: 'Pro at $39 and Scale at $79 per house per month, printed large with the unit small, on the front page and on /pricing.',
    probe: [{ home: '$39<small> / house / mo</small>' }, { home: '$79<small> / house / mo</small>' }, { html: 'Signing up takes five minutes' }] },
  { id: 'ch-17', name: 'The address — write, copy, open', kind: 'email',
    what: 'shift@cohorthome.app is a mailto everywhere it is printed, with a copy button that also opens the mail app.',
    probe: [{ home: 'mailto:shift@cohorthome.app' }, { home: 'data-copy="shift@cohorthome.app"' }, { home: 'class="copyb"' }, { home: 'class="ssheet-f"' }] },
  { id: 'ch-18', name: 'Share this page', kind: 'footer',
    what: 'A share control in the footer and in the phone menu uses the native share sheet, or copies the link.',
    probe: [{ home: 'data-share' }, { home: 'Share this page' }] },
  { id: 'ch-19', name: 'Larger text', kind: 'a11y',
    what: 'A switch bumps the body size 1.15× and is remembered.',
    probe: [{ home: 'data-text-toggle' }, { css: 'html[data-text="lg"]' }, { js: "'pho-text'" }] },
  { id: 'ch-20', name: 'Back to the top', kind: 'navigation',
    what: 'A back-to-top control appears once the reader is past the middle of the shift.',
    probe: [{ home: 'class="totop"' }, { home: 'Top</span></a>' }, { js: 'totop' }] },
  { id: 'ch-21', name: 'The end-of-shift footer', kind: 'footer',
    what: 'The footer is the end-of-shift sheet: three lean groups, the live Oregon time, a calm seal, and the byline with the legal line.',
    probe: [{ home: 'class="eos"' }, { home: 'class="eos-d"' }, { home: 'class="eos-sign"' }, { home: 'class="stampl"' }, { home: 'class="eos-legal"' }, { js: "'.eos-d'" }] },
  { id: 'ch-22', name: 'Next, floating', kind: 'navigation',
    what: 'A small pill at the bottom-left appears once the reader is well into a page and names the page after it.',
    probe: [{ home: 'class="nxt' }, { home: 'data-next' }, { html: 'href="/screens" data-next' }] },
  { id: 'ch-23', name: 'Paper, then the record', kind: 'interaction',
    what: 'A before/after handle between a hand-written MAR line and the stamped entry, driven by pointer or keyboard.',
    probe: [{ home: 'class="cmp-r"' }, { home: 'class="paper-ink"' }, { css: 'clip-path:inset(0 calc(100% - var(--x' }] },
  { id: 'ch-24', name: 'The two stops turn over', kind: 'interaction',
    what: 'Each stop is a card: the front is the stop, the back is what going on records.',
    probe: [{ home: 'data-flip' }, { home: 'class="gate-b"' }, { js: 'is-flipped' }] },
  { id: 'ch-25', name: 'Who is holding the phone', kind: 'interaction',
    what: 'A Now / Day / Night control on the roles grid highlights the roles on shift, each with its own icon.',
    probe: [{ home: 'data-shift="night"' }, { home: 'data-roles' }, { home: 'class="role-ic"' }, { js: 'onShift' }] },
  { id: 'ch-26', name: 'Deep links that copy themselves', kind: 'navigation',
    what: 'Every hour on the timeline is its own link (#0800), and every heading grows a link icon that copies the section’s URL.',
    probe: [{ home: 'href="#0800"' }, { home: 'id="1845"' }, { js: "className = 'h-link'" }, { css: '.h-link{' }] },
  { id: 'ch-27', name: 'Write to a person', kind: 'page',
    what: 'The contact page carries the shared contact form with topics set for Cohort — Early access, A demo, Pricing, Security and privacy, Press, Something else.',
    probe: [{ route: 'contact' }, { html: '<option value="A demo">' }, { html: 'id="contactform"' }] },
  { id: 'ch-28', name: 'The social stamps', kind: 'social',
    what: 'Eight round stamped glyphs in the footer that ink on hover or press.',
    probe: [{ home: 'class="soc stamps"' }, { css: '.stamps .soc-i:hover' }, { re: '(class="soc-i"[^>]*>[\\s\\S]*?){8}' }] },
  { id: 'ch-29', name: 'The film strip of all five screens', kind: 'screen',
    what: 'A full-bleed rail on /screens carrying every real surface at the size it ships, snapped, draggable, arrow-key driven.',
    probe: [{ route: 'screens' }, { html: 'id="strip-cohort-marpass"' }, { html: 'id="strip-cohort-residents"' }, { css: '.fs-rail{' },
      { js: "live.textContent = (i + 1) + ' of ' + el.length + ', '" }] },
  { id: 'ch-30', name: 'A hero device whose screen changes', kind: 'screen',
    what: 'The phone in the hero is a real tablist over the two ends of a shift — Today and Handoff.',
    probe: [{ home: 'id="sw-hero"' }, { home: 'role="tabpanel"' }, { home: 'data-sw-to="1"' }, { home: 'class="swx-tab"' }, { js: 'const swSet = (box, i, move) => {' }] },
  { id: 'ch-31', name: 'The allergy stop, pin by pin', kind: 'screen',
    what: 'Four numbered pins over the real MAR-pass screen on /screens, each measured from the element it names.',
    probe: [{ html: 'id="cal-pass"' }, { html: 'data-sel=".sheet-h"' }, { html: 'class="cal-list"' }, { css: '.cal-pin[data-on]' },
      { js: "pin.style.setProperty('--x', pct(q.left + q.width / 2 - b.left, b.width));" }] },
  { id: 'ch-32', name: 'On this page', kind: 'navigation',
    what: 'A clean index under the hero — nine stops, no hour stamps; the one you are reading underlines itself as you scroll, and the last chip is the way to all five screens.',
    probe: [{ home: 'class="pidx"' }, { home: 'class="pidx-all"' }, { css: '.pidx-a[aria-current]::after' }, { re: '(class="pidx-a"[\\s\\S]*?){9}' }] },
  { id: 'ch-33', name: 'Jump to a screen by name', kind: 'navigation',
    what: 'The command palette lists the five product screens beside the verbs and the pages.',
    probe: [{ home: 'data-kind="screen"' }, { home: '/screens#strip-cohort-handoff' }, { css: '.pal-r[data-kind="screen"]' }] },
  { id: 'ch-34', name: 'Every screen has an address', kind: 'navigation',
    what: 'A list of the five absolute deep links on /screens, each with a copy button.',
    probe: [{ html: 'class="dl-l"' }, { html: 'data-copy="https://cohorthome.app/screens#strip-cohort-today"' }, { html: 'class="dl-u"' }, { css: '.dl-u{' }] },
  { id: 'ch-35', name: 'The four words a dose can carry', kind: 'honesty',
    what: 'Due, Overdue, Given, Held — drawn in the product’s own state chips, verbatim from the state set.',
    probe: [{ home: 'class="stleg"' }, { home: 'data-state="overdue"' }, { css: '.stleg .st-a' }] },
  { id: 'ch-36', name: 'The first ten minutes, on the screen that does it', kind: 'navigation',
    what: 'Each of the five first actions carries the screen it happens on, as a link straight into that screen on /screens.',
    probe: [{ home: 'class="ftn"' }, { home: 'class="ftn-s"' }, { css: '.ftn-s{' }] },
  { id: 'ch-37', name: 'A route that is nothing but the product', kind: 'page',
    what: '/screens carries the whole product — the five-screen strip, the annotated pass, the desktop, and the addresses.',
    probe: [{ route: 'screens' }, { home: 'href="/screens"' }, { html: 'Every screen, at the size it ships.' }] },
  { id: 'ch-38', name: 'The same record, on the desktop, annotated', kind: 'screen',
    what: 'Today on the desktop app at a size it can be read at, with three numbered pins.',
    probe: [{ html: 'id="cal-desktop"' }, { html: 'Today, on the desktop app' }, { html: 'data-sel=".tbl-a"' }, { html: 'class="shell-w"' }, { css: '#cal-desktop .browser{--mock-z:.8}' }] },
  { id: 'ch-39', name: 'The five screens, in the phone menu', kind: 'mobile',
    what: 'The phone menu carries a numbered row of the five screens above the stops.',
    probe: [{ home: 'class="ssheet-sc"' }, { home: 'class="ssheet-scr"' }, { css: '.ssheet-scr a' }, { js: "const holders = $$('[data-page-index]');" }] },
  { id: 'ch-40', name: 'Seven states, two of them stops', kind: 'interaction',
    what: 'The medication pass drawn as its own state machine on /features, with the two that can stop a caregiver marked.',
    probe: [{ html: 'class="pass"' }, { html: 'data-stop="2"' }, { css: '.pass-s[data-stop]' }] },
  { id: 'ch-41', name: 'A correction is an addendum', kind: 'interaction',
    what: 'The original entry and the addendum under it, both stamped, beside the four words a dose can carry.',
    probe: [{ home: 'class="adden"' }, { home: 'class="adden-r is-add"' }, { home: 'class="corr"' }, { css: '.adden-r.is-add' }] },
  { id: 'ch-42', name: 'Refused on principle', kind: 'honesty',
    what: 'Four things Cohort will not do — a third stop, deleting, editing a filed incident, recording care in bulk — as four short cards on /features, each with its reason.',
    probe: [{ html: 'class="ref-g"' }, { html: 'A third stop' }, { html: 'Recording care in bulk' }, { css: '.ref-g{' }, { re: '(class="ref-c"[\\s\\S]*?){4}' }] },
  { id: 'ch-43', name: 'The shift opens on a phone', kind: 'mobile',
    what: 'On a phone the page opens as an index, and the shift — the centrepiece — starts open rather than folded.',
    probe: [{ home: 'data-phone-open' }, { js: "s.hasAttribute('data-phone-open')" }] },
  { id: 'ch-44', name: 'Your house, in one line', kind: 'conversion',
    what: 'The door to app.cohorthome.app with a one-line CTA row and three facts with their own icons.',
    probe: [{ home: 'class="ctas house-c"' }, { home: 'class="house-ki"' }, { home: 'class="door"' }] },
  { id: 'ch-45', name: 'Icon-only controls say what they do', kind: 'a11y',
    what: 'Every icon-only control in the chrome carries a meaningful aria-label, which the shared script turns into a hover tooltip.',
    probe: [{ home: 'aria-label="Search this site"' }, { home: 'aria-label="Switch to night shift"' }, { js: "el.setAttribute('data-tip', el.getAttribute('aria-label'));" }] },
];

export default FEATURES;
