// The twenty-five things the Cohort site does, each checked against the
// built bytes by tools/check.mjs. A probe is chosen so that removing the
// feature would make it fail.

export const FEATURES = [
  { id: 'ch-01', name: 'The time rail', kind: 'navigation',
    what: 'The header navigation is a rail of stops labelled with the hour of the shift; a coral now-dot travels it with the scroll and the current stop fills.',
    probe: [{ home: 'class="rail"' }, { home: 'class="rail-now"' }, { js: "setProperty('--now'" }] },
  { id: 'ch-02', name: 'The shift sheet', kind: 'mobile',
    what: 'On a phone the menu is a full-screen sheet in the idiom of the app’s handoff sheet, listing the stops with their hours, the pages, the day/night switch and the text-size switch.',
    probe: [{ home: 'id="sheet"' }, { home: 'class="ssheet-hr"' }, { css: '.ssheet{' }] },
  { id: 'ch-03', name: 'The phone tab bar, with the mark in the centre', kind: 'mobile',
    what: 'A fixed, safe-area-aware bottom bar mirrors the app’s tab bar — Today, Shift, the mark as the door to your house, Record, Join — and marks the section in view.',
    probe: [{ home: 'class="tabs"' }, { home: 'class="tab-s tab-m"' }, { css: 'env(safe-area-inset-bottom)' }, { js: "'.tabs[data-tabs]'" }] },
  { id: 'ch-04', name: 'Day shift / Night shift', kind: 'dark',
    what: 'The dark-mode switch is a shift badge; night shift is a real palette — deep teal-black ground, ivory type, the coral unchanged — and it reaches the phones on the page.',
    probe: [{ home: 'data-mode-toggle' }, { home: 'class="shiftb-n"' }, { css: 'html[data-mode="dark"]{' }, { js: 'phoneMode' }] },
  { id: 'ch-05', name: 'It is <time> in Oregon', kind: 'interaction',
    what: 'The hero carries a live Pacific-time clock and what the demo shift has due this hour, computed from the day on the page.',
    probe: [{ home: 'data-oregon' }, { home: 'data-due' }, { js: "'America/Los_Angeles'" }] },
  { id: 'ch-06', name: 'The phone that follows the hours', kind: 'screen',
    what: 'A timeline of the shift with a phone beside it that changes screen at each hour; on phones the screen becomes a sticky cropped strip at the top of the section.',
    probe: [{ home: 'class="tour-p' }, { home: 'data-tour="incident"' }, { css: '.crop{' }, { home: 'data-tour-cap' }] },
  { id: 'ch-07', name: 'Keys: J, K, arrows and ?', kind: 'a11y',
    what: 'J and K step the timeline, the arrows do the same while an hour is focused, T goes back to 06:55, and ? opens a shortcut sheet.',
    probe: [{ home: 'id="keys"' }, { js: "e.key === 'j'" }, { js: "e.key === '?'" }] },
  { id: 'ch-08', name: 'The MAR-pass simulator', kind: 'screen',
    what: 'In the 08:00 step the phone is interactive: tap a due row, the Six Rights sheet slides up, Sign marks it Given with “Logged by you · time”; loratadine raises the allergy gate and asks for a reason first.',
    probe: [{ home: 'data-tour="marpass+sheet"' }, { home: 'class="sim-reset"' }, { js: 'is-sim' }, { js: 'Override and sign' }] },
  { id: 'ch-09', name: 'Airplane mode', kind: 'interaction',
    what: 'A switch beside the 10:30 step: on, new care notes queue with a pending chip and an outbox count on the page and on the phone; off, they catch up one by one with stamps.',
    probe: [{ home: 'class="air-sw"' }, { home: 'class="air-out"' }, { js: 'data-pending' }] },
  { id: 'ch-10', name: 'The handoff composes itself', kind: 'motion',
    what: 'As the 18:45 step comes into view the sheet on the phone fills in line by line — MAR 18 of 18, Documentation 9 of 9 — driven by an IntersectionObserver.',
    probe: [{ home: 'data-tour="handoff+compose"' }, { css: '.is-compose:not(.is-done)' }, { js: 'IntersectionObserver' }] },
  { id: 'ch-11', name: '⌘K — the product’s verbs', kind: 'navigation',
    what: 'A command palette listing the product’s own verbs — Sign a dose, File an incident, Start handover, Add an addendum — plus the stops and the pages; typeahead, arrow keys, Escape.',
    probe: [{ home: 'id="pal"' }, { home: 'Sign a dose' }, { js: 'e.metaKey' }, { js: 'pal-none' }] },
  { id: 'ch-12', name: 'Print the manifesto', kind: 'print',
    what: 'A print button on the refusals; the print stylesheet prints only the manifesto, numbered, on one page.',
    probe: [{ home: 'data-print-only="refuses"' }, { css: 'html[data-print="manifesto"]' }, { js: 'afterprint' }] },
  { id: 'ch-13', name: 'The questions, filtered', kind: 'interaction',
    what: 'A filter box above the questions narrows the disclosures by text as you type and counts “n of 4”.',
    probe: [{ home: 'class="faq-q"' }, { home: 'class="faq-n"' }, { js: 'faq-none' }] },
  { id: 'ch-14', name: 'Pricing by houses', kind: 'interaction',
    what: 'A 1 · 2–3 · 4–9 · 10+ stepper rewrites the tier line, marks the tier that covers you, and presets the waitlist’s house count — without inventing a price.',
    probe: [{ home: 'class="hs"' }, { home: 'class="hs-line"' }, { js: "select[name=\"houses\"]" }, { route: 'pricing' }] },
  { id: 'ch-15', name: 'hello@ — write, copy', kind: 'email',
    what: 'The address is a mailto everywhere it is printed, with a copy button that toasts.',
    probe: [{ home: 'mailto:hello@cohorthome.app' }, { home: 'data-copy="hello@cohorthome.app"' }, { home: 'class="copyb"' }] },
  { id: 'ch-16', name: 'Share this page', kind: 'footer',
    what: 'A share control in the end-of-shift footer and in the shift sheet uses the native share sheet, or copies the link.',
    probe: [{ home: 'data-share' }, { home: 'Share this page' }] },
  { id: 'ch-17', name: 'Larger text', kind: 'a11y',
    what: 'An A/A+ switch bumps the body size 1.15× and is remembered — caregivers over fifty read on phones.',
    probe: [{ home: 'data-text-toggle' }, { css: 'html[data-text="lg"]' }, { js: "'pho-text'" }] },
  { id: 'ch-18', name: 'Back to 06:55', kind: 'navigation',
    what: 'A back-to-top control labelled with the shift’s first hour appears once the reader is past the middle of the shift.',
    probe: [{ home: 'class="totop"' }, { home: '06:55</span></a>' }, { js: 'totop' }] },
  { id: 'ch-19', name: 'The end-of-shift sheet', kind: 'footer',
    what: 'The footer is laid out as the handoff sheet the product composes at 18:45 — four sheet rows, then the live Oregon time, the stamp-logo and the byline; on phones the rows fold into an accordion of details.',
    probe: [{ home: 'class="eos"' }, { home: 'class="eos-d"' }, { home: 'class="eos-sign"' }, { js: "'.eos-d'" }] },
  { id: 'ch-20', name: 'Paper, then the record', kind: 'interaction',
    what: 'A before/after handle on the record section between a hand-written MAR line and the stamped entry, driven by pointer or keyboard.',
    probe: [{ home: 'class="cmp-r"' }, { home: 'class="paper-ink"' }, { css: 'clip-path:inset(0 calc(100% - var(--x' }] },
  { id: 'ch-21', name: 'The two stops turn over', kind: 'interaction',
    what: 'Each gate is a card: the front is the stop, the back is what the override records — a reason of ten characters, on the dose, in the audit log, and the manager told.',
    probe: [{ home: 'data-flip' }, { home: 'class="gate-b"' }, { js: 'is-flipped' }] },
  { id: 'ch-22', name: 'Who is holding the phone', kind: 'interaction',
    what: 'A Now / Day / Night control on the roles grid highlights the roles on shift — Now from the live clock: day 06:55–19:00, night otherwise.',
    probe: [{ home: 'data-shift="night"' }, { home: 'data-roles' }, { js: 'onShift' }] },
  { id: 'ch-23', name: 'Deep links that copy themselves', kind: 'navigation',
    what: 'Every hour on the timeline is its own link (#0800), and every heading grows a link icon that copies the section’s URL.',
    probe: [{ home: 'href="#0800"' }, { home: 'id="1845"' }, { js: "className = 'h-link'" }, { css: '.h-link{' }] },
  { id: 'ch-24', name: 'Write to a person', kind: 'page',
    what: 'The contact page carries the shared contact form with topics set for Cohort — Early access, The pilot, Pricing, Security and privacy, Press, Something else.',
    probe: [{ route: 'contact' }, { html: '<option value="The pilot">' }, { html: 'id="contactform"' }] },
  { id: 'ch-25', name: 'The social stamps', kind: 'social',
    what: 'Eight round stamped glyphs in the footer that ink on hover or press, with the handle as a tooltip on desktop and as a label on phones.',
    probe: [{ home: 'class="soc stamps"' }, { css: '.stamps .soc-i:hover' }, { re: '(class="soc-i"[^>]*>[\\s\\S]*?){8}' }] },
];

export default FEATURES;
