// The twenty-five things the Cohort site does, each checked against the
// built bytes by tools/check.mjs. A probe is chosen so that removing the
// feature would make it fail.

export const FEATURES = [
  { id: 'ch-01', name: 'The time rail', kind: 'navigation',
    what: 'The header navigation is a rail of stops labelled with the hour of the shift; a coral now-dot travels it with the scroll and the current stop fills.',
    probe: [{ home: 'class="rail"' }, { home: 'class="rail-now"' }, { js: "setProperty('--now'" }] },
  { id: 'ch-02', name: 'The shift sheet', kind: 'mobile',
    what: 'On a phone the menu is a full-screen sheet in the idiom of the app’s handoff sheet, listing the stops with their hours, the pages, the day/night switch and the text-size switch.',
    probe: [{ home: 'id="sheet"' }, { home: 'class="ssheet-hr"' }, { css: '.ssheet{' }] },
  { id: 'ch-03', name: 'The phone tab bar, with the mark in the centre', kind: 'mobile',
    what: 'A fixed, safe-area-aware bottom bar mirrors the app’s tab bar — Today, Shift, the mark as the door to your house, Record, Join — and marks the section in view.',
    probe: [{ home: 'class="tabs"' }, { home: 'class="tab-s tab-m"' }, { css: 'env(safe-area-inset-bottom)' }, { js: "'.tabs[data-tabs]'" }] },
  { id: 'ch-04', name: 'Day shift / Night shift', kind: 'dark',
    what: 'The dark-mode switch is a shift badge; night shift is a real palette — deep teal-black ground, ivory type, the coral unchanged — and it reaches the phones on the page.',
    probe: [{ home: 'data-mode-toggle' }, { home: 'class="shiftb-n"' }, { css: 'html[data-mode="dark"]{' }, { js: 'phoneMode' }] },
  { id: 'ch-05', name: 'It is <time> in Oregon', kind: 'interaction',
    what: 'The hero carries a live Pacific-time clock and what the demo shift has due this hour, computed from the day on the page.',
    probe: [{ home: 'data-oregon' }, { home: 'data-due' }, { js: "'America/Los_Angeles'" }] },
  { id: 'ch-06', name: 'The phone that follows the hours', kind: 'screen',
    what: 'A timeline of the shift with a phone beside it that changes screen at each hour; on phones the screen becomes a sticky cropped strip at the top of the section.',
    probe: [{ home: 'class="tour-p' }, { home: 'data-tour="incident"' }, { css: '.crop{' }, { home: 'data-tour-cap' }] },
  { id: 'ch-07', name: 'Keys: J, K, arrows and ?', kind: 'a11y',
    what: 'J and K step the timeline, the arrows do the same while an hour is focused, T goes back to 06:55, and ? opens a shortcut sheet.',
    probe: [{ home: 'id="keys"' }, { js: "e.key === 'j'" }, { js: "e.key === '?'" }] },
  { id: 'ch-08', name: 'The MAR-pass simulator', kind: 'screen',
    what: 'In the 08:00 step the phone is interactive: tap a due row, the Six Rights sheet slides up, Sign marks it Given with “Logged by you · time”; loratadine raises the allergy gate and asks for a reason first.',
    probe: [{ home: 'data-tour="marpass+sheet"' }, { home: 'class="sim-reset"' }, { js: 'is-sim' }, { js: 'Override and sign' }] },
  { id: 'ch-09', name: 'Airplane mode', kind: 'interaction',
    what: 'A switch beside the 10:30 step: on, new care notes queue with a pending chip and an outbox count on the page and on the phone; off, they catch up one by one with stamps.',
    probe: [{ home: 'class="air-sw"' }, { home: 'class="air-out"' }, { js: 'data-pending' }] },
  { id: 'ch-10', name: 'The handoff composes itself', kind: 'motion',
    what: 'As the 18:45 step comes into view the sheet on the phone fills in line by line — MAR 18 of 18, Documentation 9 of 9 — driven by an IntersectionObserver.',
    probe: [{ home: 'data-compose-note' }, { css: '.is-compose:not(.is-done)' }, { js: "classList.add('is-compose')" }] },
  { id: 'ch-11', name: '⌘K — the product’s verbs', kind: 'navigation',
    what: 'A command palette listing the product’s own verbs — Sign a dose, File an incident, Start handover, Add an addendum — plus the stops and the pages; typeahead, arrow keys, Escape.',
    probe: [{ home: 'id="pal"' }, { home: 'Sign a dose' }, { js: 'e.metaKey' }, { js: 'pal-none' }] },
  { id: 'ch-12', name: 'Print the manifesto', kind: 'print',
    what: 'A print button on the refusals; the print stylesheet prints only the manifesto, numbered, on one page.',
    probe: [{ home: 'data-print-only="refuses"' }, { css: 'html[data-print="manifesto"]' }, { js: 'afterprint' }] },
  { id: 'ch-13', name: 'The questions, filtered', kind: 'interaction',
    what: 'A filter box above the questions narrows the disclosures by text as you type and counts “n of 4”.',
    probe: [{ home: 'class="faq-q"' }, { home: 'class="faq-n"' }, { js: 'faq-none' }] },
  { id: 'ch-14', name: 'Pricing by houses', kind: 'interaction',
    what: 'A 1 · 2–3 · 4–9 · 10+ stepper rewrites the tier line, marks the tier that covers you, and presets the waitlist’s house count — without inventing a price.',
    probe: [{ home: 'class="hs"' }, { home: 'class="hs-line"' }, { js: "select[name=\"houses\"]" }, { route: 'pricing' }] },
  { id: 'ch-15', name: 'hello@ — write, copy', kind: 'email',
    what: 'The address is a mailto everywhere it is printed, with a copy button that toasts.',
    probe: [{ home: 'mailto:hello@cohorthome.app' }, { home: 'data-copy="hello@cohorthome.app"' }, { home: 'class="copyb"' }] },
  { id: 'ch-16', name: 'Share this page', kind: 'footer',
    what: 'A share control in the end-of-shift footer and in the shift sheet uses the native share sheet, or copies the link.',
    probe: [{ home: 'data-share' }, { home: 'Share this page' }] },
  { id: 'ch-17', name: 'Larger text', kind: 'a11y',
    what: 'An A/A+ switch bumps the body size 1.15× and is remembered — caregivers over fifty read on phones.',
    probe: [{ home: 'data-text-toggle' }, { css: 'html[data-text="lg"]' }, { js: "'pho-text'" }] },
  { id: 'ch-18', name: 'Back to 06:55', kind: 'navigation',
    what: 'A back-to-top control labelled with the shift’s first hour appears once the reader is past the middle of the shift.',
    probe: [{ home: 'class="totop"' }, { home: '06:55</span></a>' }, { js: 'totop' }] },
  { id: 'ch-19', name: 'The end-of-shift sheet', kind: 'footer',
    what: 'The footer is laid out as the handoff sheet the product composes at 18:45 — four sheet rows, then the live Oregon time, the stamp-logo and the byline; on phones the rows fold into an accordion of details.',
    probe: [{ home: 'class="eos"' }, { home: 'class="eos-d"' }, { home: 'class="eos-sign"' }, { js: "'.eos-d'" }] },
  { id: 'ch-20', name: 'Paper, then the record', kind: 'interaction',
    what: 'A before/after handle on the record section between a hand-written MAR line and the stamped entry, driven by pointer or keyboard.',
    probe: [{ home: 'class="cmp-r"' }, { home: 'class="paper-ink"' }, { css: 'clip-path:inset(0 calc(100% - var(--x' }] },
  { id: 'ch-21', name: 'The two stops turn over', kind: 'interaction',
    what: 'Each gate is a card: the front is the stop, the back is what the override records — a reason of ten characters, on the dose, in the audit log, and the manager told.',
    probe: [{ home: 'data-flip' }, { home: 'class="gate-b"' }, { js: 'is-flipped' }] },
  { id: 'ch-22', name: 'Who is holding the phone', kind: 'interaction',
    what: 'A Now / Day / Night control on the roles grid highlights the roles on shift — Now from the live clock: day 06:55–19:00, night otherwise.',
    probe: [{ home: 'data-shift="night"' }, { home: 'data-roles' }, { js: 'onShift' }] },
  { id: 'ch-23', name: 'Deep links that copy themselves', kind: 'navigation',
    what: 'Every hour on the timeline is its own link (#0800), and every heading grows a link icon that copies the section’s URL.',
    probe: [{ home: 'href="#0800"' }, { home: 'id="1845"' }, { js: "className = 'h-link'" }, { css: '.h-link{' }] },
  { id: 'ch-24', name: 'Write to a person', kind: 'page',
    what: 'The contact page carries the shared contact form with topics set for Cohort — Early access, The pilot, Pricing, Security and privacy, Press, Something else.',
    probe: [{ route: 'contact' }, { html: '<option value="The pilot">' }, { html: 'id="contactform"' }] },
  { id: 'ch-25', name: 'The social stamps', kind: 'social',
    what: 'Eight round stamped glyphs in the footer that ink on hover or press, with the handle as a tooltip on desktop and as a label on phones.',
    probe: [{ home: 'class="soc stamps"' }, { css: '.stamps .soc-i:hover' }, { re: '(class="soc-i"[^>]*>[\\s\\S]*?){8}' }] },

  /* ══ THE WORKING DEMO ═══════════════════════════════════════════════════
     Twenty-five more, and the direction they were built to: a partner with
     ninety seconds must be able to OPERATE the product inside the page and
     leave knowing exactly what is and is not true. Ten of them are the
     family backbone, drawn in this site's own metaphor — the shift; the
     other fifteen come out of Cohort's own material and nowhere else.
     PROBES. tools/check.mjs is substring matching over the built bytes —
     four kinds: {home} and {html} read the HTML, {css} the stylesheet, {js}
     the script. That means a probe can only prove that the BYTES a feature
     needs are present; no probe here runs the page, and none of them can
     tell a working film strip from a dead one.

     What it CAN do, and did not before this round: every feature below
     whose sentence describes a BEHAVIOUR now names the line of script that
     performs it, so deleting the code breaks the build rather than passing
     it quietly. Until this round ch-26…ch-50 carried 87 probes and not one
     of them read the JS: site.js demos() — the film strip, the hero
     switcher, the callout pins — could be deleted whole and check.mjs still
     printed "50 features verified". It cannot now: nine of the twenty-five
     carry fourteen {js} probes between them, and every one of those is a
     line that exists only because the behaviour does. Four of the fourteen
     sit INSIDE demos() rather than in a helper it calls, so deleting that
     one function fails the build on ch-26, ch-27 and ch-28 instead of
     passing it quietly. The other sixteen features are markup and
     stylesheet, and their probes say so. */

  { id: 'ch-26', name: 'The film strip of all five screens', kind: 'screen',
    what: 'A full-bleed rail on /screens carrying every real surface — Today, the MAR pass, an incident, the handoff, the resident record — at the size it ships, snapped, draggable, arrow-key driven, each captioned with what it proves.',
    probe: [{ route: 'screens' }, { html: 'id="strip-cohort-marpass"' }, { html: 'id="strip-cohort-residents"' }, { css: '.fs-rail{' },
      { js: "live.textContent = (i + 1) + ' of ' + el.length + ', '" },
      { js: "if (e.pointerType !== 'mouse' || e.button) return;" },
      { js: "if (t && t.closest(RAIL)) t.scrollIntoView({ inline: 'start', block: 'nearest' });" }] },
  { id: 'ch-27', name: 'A hero device whose screen changes', kind: 'screen',
    what: 'The phone in the hero is a real tablist over the two ends of a shift — 06:55 Today and 18:45 Handoff. Every panel keeps its box in one grid cell, so changing screen moves nothing; with scripting off the screens simply stack.',
    probe: [{ home: 'id="sw-hero"' }, { home: 'role="tabpanel"' }, { home: 'data-sw-to="1"' }, { home: 'class="swx-tab"' },
      { js: 'const swSet = (box, i, move) => {' },
      { js: "const boxes = $$('[data-switch]');" }] },
  { id: 'ch-28', name: 'The allergy gate, pin by pin', kind: 'screen',
    what: 'Four numbered pins over the real MAR-pass screen on /screens — the Six Rights dialog, the allergy stop, the interval stop and what an override costs. Each pin is measured from the element it quotes, so a stale selector leaves no orphan; pointing at a sentence lights the pin and the element together.',
    probe: [{ html: 'id="cal-pass"' }, { html: 'data-sel=".sheet-h"' }, { html: 'class="cal-list"' }, { css: '.cal-pin[data-on]' },
      { js: "pin.style.setProperty('--x', pct(q.left + q.width / 2 - b.left, b.width));" },
      { js: 'const ro = new ResizeObserver((entries) => {' },
      { js: "addEventListener('resize', place, { passive: true });" }] },
  { id: 'ch-29', name: 'What is on this page', kind: 'navigation',
    what: 'A strip of stops under the hero, each carrying the hour the shift gives it; the one you are reading marks itself as you scroll, and the last chip is the way to all five screens.',
    probe: [{ home: 'class="pidx"' }, { home: 'class="pidx-all"' }, { css: '.pidx-a[aria-current]' }, { re: '(class="pidx-a"[\\s\\S]*?){12}' },
      { js: "const navs = $$('[data-spy]').map((n) => {" }] },
  { id: 'ch-30', name: 'Previous and next, across the eight routes', kind: 'navigation',
    what: 'Every page ends with the page before it and the page after it, named, with the line that says what is there. No script: it works with JS off and it prints.',
    probe: [{ home: 'class="eos-pn"' }, { home: 'data-pn="next"' }, { html: 'data-pn="prev"' }, { css: '.eos-pn{' }] },
  { id: 'ch-31', name: 'Jump to a screen by name', kind: 'navigation',
    what: 'The command palette lists the five product screens beside the verbs and the pages; typing “handoff” lands on that screen on /screens rather than at the top of a route.',
    probe: [{ home: 'data-kind="screen"' }, { home: '/screens#strip-cohort-handoff' }, { css: '.pal-r[data-kind="screen"]' },
      { js: 'if (it.name.startsWith(q)) return 3;' },
      { css: '.tr-tools{display:flex}' }] },
  { id: 'ch-32', name: 'The status ledger', kind: 'honesty',
    what: 'Five rows saying what is live, what is partly true and what is not built — the site, the product, the pilot home, the prices and the door — each with the reason, and no row carrying a number the vault has not set.',
    probe: [{ home: 'class="ledg"' }, { home: 'data-live="part"' }, { home: 'data-live="no"' }, { css: '.ledg-r[data-live="no"]' }] },
  { id: 'ch-33', name: 'The family band', kind: 'family',
    what: 'The other three rooms of the house — CareShop, Binderkit, Aidepost — each with its own mark, its own domain and its own standing, live and linked, with Cohort marked as the room you are in.',
    probe: [{ home: 'class="room is-here"' }, { home: 'https://careshop.app' }, { home: 'https://binderkit.com' }, { home: 'https://aidepost.com' }, { css: '.room-mk' }] },
  { id: 'ch-34', name: 'The graduation path', kind: 'family',
    what: 'Four steps from one house to twenty: Cohort runs the shift, the export is generated in the client with redaction on, Provider Hub Oregon imports it directly because the record is already in its shape, and the roll-up begins.',
    probe: [{ home: 'class="grad-l"' }, { home: 'data-grad="3"' }, { home: 'data-grad="4"' }, { css: '.grad-l{' }] },
  { id: 'ch-35', name: 'Every screen has an address', kind: 'navigation',
    what: 'A list of the five absolute deep links on /screens, each with a copy button; the link opens on that screen aligned to the start of the rail rather than wherever the browser lands.',
    probe: [{ html: 'class="dl-l"' }, { html: 'data-copy="https://cohorthome.app/screens#strip-cohort-today"' }, { html: 'class="dl-u"' }, { css: '.dl-u{' },
      { js: "const text = c.getAttribute('data-copy') || c.textContent.trim();" }] },

  { id: 'ch-36', name: 'The boundary, as a map', kind: 'honesty',
    what: 'The five things Cohort refuses to be, each naming the room that does hold it — and the one that names nowhere, because policing compliance is not a product in this family.',
    probe: [{ home: 'class="bmap-l"' }, { home: 'class="bmap-to is-none"' }, { css: '.bmap-w::before' }] },
  { id: 'ch-37', name: 'The pilot, with a falsifiable exit', kind: 'honesty',
    what: 'The named AFH-DD in Eugene, the fourteen-consecutive-day exit criterion, and the line no real resident crosses until the customer business associate agreement is executed — as a ledger row and as one of the three checkable claims.',
    probe: [{ home: 'The pilot home' }, { home: 'Fourteen consecutive days' }, { home: 'not executed' }] },
  { id: 'ch-38', name: 'The four words this product owns', kind: 'honesty',
    what: 'Due, Overdue, Given, Held — drawn in the product’s own state chips, verbatim from the state set, with the rule beside them: overdue is a deeper coral and nothing on this site is red.',
    probe: [{ home: 'class="stleg"' }, { home: 'data-state="overdue"' }, { home: 'deeper coral' }, { css: '.stleg .st-a' }] },
  { id: 'ch-39', name: 'The first ten minutes, on the screen that does it', kind: 'navigation',
    what: 'Each of the five first actions carries the screen it happens on, as a link straight into that screen on /screens.',
    probe: [{ home: 'class="ftn"' }, { home: 'class="ftn-s"' }, { css: '.ftn-s{' }] },
  { id: 'ch-40', name: 'Sample data, said out loud', kind: 'honesty',
    what: 'The two places on the front page where a rendered screen sits next to prose carry the same coral-dotted mark saying the screens use sample data — beside the hero device and under the shift timeline. /screens carries no badge and says it in prose instead, twice: once in the page lede and once in the strip’s own hint. The footer states it a third time in words.',
    probe: [{ home: 'class="demo-b"' }, { home: 'The screens beside this use sample data' }, { css: '.demo-b::before' }] },
  { id: 'ch-41', name: 'Every refusal is its own address', kind: 'navigation',
    what: 'The eleven refusals each carry an id and a button that copies its absolute link; arriving on one lights that refusal.',
    probe: [{ home: 'id="refuse-07"' }, { home: 'class="ref-a"' }, { home: 'https://cohorthome.app/#refuse-11' }, { css: '.ref-l li:target' },
      { js: "toast(c.getAttribute('data-copied') || 'Copied');" }] },
  { id: 'ch-42', name: 'A route that is nothing but the product', kind: 'page',
    what: '/screens carries the whole product — the five-screen strip, the annotated pass, the desktop, and the addresses — where a 30 kB strip costs the front page’s byte budget nothing.',
    probe: [{ route: 'screens' }, { home: 'href="/screens"' }, { html: 'Every screen, at the size it ships.' }] },
  { id: 'ch-43', name: 'The same record, on the desktop, annotated', kind: 'screen',
    what: 'Today on the desktop app, drawn at the size it can be read at: the 1024px window at full size on a desktop, and below 900px the app’s own 768px narrow build at 80%, panned sideways inside its own scroller rather than shrunk to fit. Three numbered pins: composed at read time, the allergy surfaced rather than enforced, and a stamp at the end of every row.',
    probe: [{ html: 'id="cal-desktop"' }, { html: 'Today, on the desktop app' }, { html: 'data-sel=".tbl-a"' },
      { html: 'class="shell-w"' }, { css: '#cal-desktop .browser{--mock-z:.8}' }] },
  { id: 'ch-44', name: 'The five screens, in the shift sheet', kind: 'mobile',
    what: 'The phone menu carries a numbered row of the five screens above the stops, so the product is one thumb-reach from every route.',
    probe: [{ home: 'class="ssheet-sc"' }, { home: 'class="ssheet-scr"' }, { css: '.ssheet-scr a' },
      { js: "const holders = $$('[data-page-index]');" },
      { css: '.ssheet-h{position:sticky' }] },
  { id: 'ch-45', name: 'Seven states, two of them stops', kind: 'interaction',
    what: 'The medication pass drawn as its own state machine on /features — scheduled, Six Rights, allergy check, interval and ceiling, witness co-sign, signed, locked — with the two that can stop a caregiver marked and nothing else marked at all.',
    probe: [{ html: 'class="pass"' }, { html: 'data-stop="2"' }, { css: '.pass-s[data-stop]' }] },
  { id: 'ch-46', name: 'A correction is an addendum', kind: 'interaction',
    what: 'The original entry and the addendum under it, both stamped, with the sentence that there is no third row: the state machine has no transition that edits or removes the first.',
    probe: [{ home: 'class="adden"' }, { home: 'class="adden-r is-add"' }, { css: '.adden-r.is-add' }] },
  { id: 'ch-47', name: 'Three inks, and what each one marks', kind: 'honesty',
    what: 'The page’s own palette, named: teal for structure, coral for the one thing coral marks — late, unread or waiting on a decision — and ink for the record itself. A claim a reader can check against the pixels.',
    probe: [{ home: 'class="inks"' }, { home: 'data-ink="coral"' }, { css: '.inks-i[data-ink="coral"] dt i' }] },
  { id: 'ch-48', name: 'The keys reach the demo', kind: 'a11y',
    what: 'The shortcut sheet documents the arrow keys and Home/End across the hero switcher and the film strip, which is where the shared rail and tablist behaviour already is.',
    probe: [{ home: 'Move across the screens' }, { home: 'The first screen, and the last' }, { home: 'id="keys"' },
      { js: 'const typing = (e) => /^(INPUT|TEXTAREA|SELECT)$/' }] },
  { id: 'ch-49', name: 'The wedge, in three checkable lines', kind: 'honesty',
    what: 'Two physical-harm gates and no third, an append-only record where a correction is an addendum, and a named pilot with a falsifiable exit — stated as the three things a partner can verify rather than as a claim about traction.',
    probe: [{ home: 'class="wedge-l"' }, { home: 'Two gates, and no third' }, { css: '.wedge-l li::before' }] },
  { id: 'ch-50', name: 'And the one thing it misses', kind: 'honesty',
    what: 'Beside the wedge, the limitation: the allergy match is by normalised name and ingredient plus a manual flag, and it misses drug-class conflicts. The product says so on the stop rather than implying a completeness it does not have.',
    probe: [{ home: 'class="note limit"' }, { home: 'drug-class conflicts' }, { css: '.limit{' }] },
];

export default FEATURES;
